# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens diploma\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\ComodelsConfigBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComodelsConfigBox(object):
    def setupUi(self, ComodelsConfigBox):
        ComodelsConfigBox.setObjectName("ComodelsConfigBox")
        ComodelsConfigBox.resize(680, 202)
        ComodelsConfigBox.setStyleSheet("QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 10px;\n"
" background-color:rgb(37, 40, 50)\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"font:22px;\n"
"font:bold;\n"
"border-color:white;\n"
"}\n"
"\n"
"/* QFrame */\n"
"QWidget {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"background-color:none;\n"
"    color: rgb(255, 255, 255);\n"
"font-size:22px;\n"
"font:normal;\n"
"\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    background-color:#1b1d23;\n"
"    color: rgb(255, 255, 255);\n"
"    margin:10px;\n"
"    padding:5px;\n"
"font:bold 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:22px;\n"
"    font:normal; \n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(\":/icons/icons/cil-chevron-bottom.png\");\n"
"    width:15px;\n"
"    height:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* LineEdit */\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"    font-size:20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"QCheckBox\n"
"{\n"
"background-color:none;\n"
"    font-size:22px;\n"
"    font:normal; \n"
"     color:white;\n"
"}\n"
"QListWidget\n"
"{\n"
"    font-size:18px;\n"
"    font:normal; \n"
"     color:white;\n"
"    background-color: rgb(52, 59, 72);\n"
"\n"
"}")
        ComodelsConfigBox.setTitle("")
        self.gridLayout = QtWidgets.QGridLayout(ComodelsConfigBox)
        self.gridLayout.setObjectName("gridLayout")
        self.HostName_Hlayout = QtWidgets.QHBoxLayout()
        self.HostName_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.HostName_Hlayout.setObjectName("HostName_Hlayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem)
        self.HostName_HSpacer_label = QtWidgets.QLabel(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostName_HSpacer_label.sizePolicy().hasHeightForWidth())
        self.HostName_HSpacer_label.setSizePolicy(sizePolicy)
        self.HostName_HSpacer_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.HostName_HSpacer_label.setObjectName("HostName_HSpacer_label")
        self.HostName_Hlayout.addWidget(self.HostName_HSpacer_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem1)
        self.HostName_comboBox = QtWidgets.QComboBox(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostName_comboBox.sizePolicy().hasHeightForWidth())
        self.HostName_comboBox.setSizePolicy(sizePolicy)
        self.HostName_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.HostName_comboBox.setObjectName("HostName_comboBox")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_Hlayout.addWidget(self.HostName_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.HostName_Hlayout, 1, 0, 1, 1)
        self.DomainId_Hlayout = QtWidgets.QHBoxLayout()
        self.DomainId_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.DomainId_Hlayout.setObjectName("DomainId_Hlayout")
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem3)
        self.DomainId_HSpacer_label = QtWidgets.QLabel(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DomainId_HSpacer_label.sizePolicy().hasHeightForWidth())
        self.DomainId_HSpacer_label.setSizePolicy(sizePolicy)
        self.DomainId_HSpacer_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DomainId_HSpacer_label.setObjectName("DomainId_HSpacer_label")
        self.DomainId_Hlayout.addWidget(self.DomainId_HSpacer_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem4)
        self.DomainId_comboBox = QtWidgets.QComboBox(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DomainId_comboBox.sizePolicy().hasHeightForWidth())
        self.DomainId_comboBox.setSizePolicy(sizePolicy)
        self.DomainId_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.DomainId_comboBox.setObjectName("DomainId_comboBox")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_Hlayout.addWidget(self.DomainId_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.DomainId_Hlayout, 2, 0, 1, 1)
        self.delete_horizontalLayout = QtWidgets.QHBoxLayout()
        self.delete_horizontalLayout.setSpacing(0)
        self.delete_horizontalLayout.setObjectName("delete_horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.delete_horizontalLayout.addItem(spacerItem6)
        self.delete_pushButton = QtWidgets.QPushButton(ComodelsConfigBox)
        self.delete_pushButton.setStyleSheet("background:none;")
        self.delete_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/frontend/IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_pushButton.setIcon(icon)
        self.delete_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.delete_horizontalLayout.addWidget(self.delete_pushButton)
        self.gridLayout.addLayout(self.delete_horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(ComodelsConfigBox)
        QtCore.QMetaObject.connectSlotsByName(ComodelsConfigBox)

    def retranslateUi(self, ComodelsConfigBox):
        _translate = QtCore.QCoreApplication.translate
        ComodelsConfigBox.setWindowTitle(_translate("ComodelsConfigBox", "GroupBox"))
        self.HostName_HSpacer_label.setText(_translate("ComodelsConfigBox", "Host Name"))
        self.HostName_comboBox.setItemText(0, _translate("ComodelsConfigBox", "Auto"))
        self.HostName_comboBox.setItemText(1, _translate("ComodelsConfigBox", "egc-med-bell"))
        self.HostName_comboBox.setItemText(2, _translate("ComodelsConfigBox", "egc-med-baird"))
        self.HostName_comboBox.setItemText(3, _translate("ComodelsConfigBox", "egc-med-nozark"))
        self.DomainId_HSpacer_label.setText(_translate("ComodelsConfigBox", "Domain Id"))
        self.DomainId_comboBox.setItemText(0, _translate("ComodelsConfigBox", "0"))
        self.DomainId_comboBox.setItemText(1, _translate("ComodelsConfigBox", "1"))
        self.DomainId_comboBox.setItemText(2, _translate("ComodelsConfigBox", "2"))
        self.DomainId_comboBox.setItemText(3, _translate("ComodelsConfigBox", "3"))
