# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens diploma\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\CompilationConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_CompilationConfig_Form(object):
    def setupUi(self, CompilationConfig_Form):
        self.setWindowIcon(QIcon('src/frontend/IconsImages/siemens_logo_icon.png'))
        CompilationConfig_Form.setObjectName("CompilationConfig_Form")
        CompilationConfig_Form.resize(619, 553)
        CompilationConfig_Form.setStyleSheet("QWidget{\n"
"    background-color: rgb(44, 49, 59);\n"
"    color: white;\n"
"    font-size: 11pt;\n"
"\n"
"}\n"
"\n"
"#MainWindow, #scrollAreaWidgetContents{\n"
"    background-color: rgb(44, 49, 59);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(CompilationConfig_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CompilationConfig_widget = QtWidgets.QWidget(CompilationConfig_Form)
        self.CompilationConfig_widget.setStyleSheet("QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(\":/icons/icons/cil-chevron-bottom.png\");\n"
"    width:15px;\n"
"    height:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"")
        self.CompilationConfig_widget.setObjectName("CompilationConfig_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CompilationConfig_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.CompilationConfig_gridLayout = QtWidgets.QGridLayout()
        self.CompilationConfig_gridLayout.setObjectName("CompilationConfig_gridLayout")
        self.Source_Output_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Source_Output_horizontalLayout.setObjectName("Source_Output_horizontalLayout")
        self.Labels_verticalLayout = QtWidgets.QVBoxLayout()
        self.Labels_verticalLayout.setObjectName("Labels_verticalLayout")
        
        self.Source_label = QtWidgets.QLabel(self.CompilationConfig_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Source_label.setFont(font)
        self.Source_label.setStyleSheet("background:none\n"
"")
        self.Source_label.setObjectName("Source_label")
        self.Labels_verticalLayout.addWidget(self.Source_label)
        
        self.Output_label = QtWidgets.QLabel(self.CompilationConfig_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Output_label.setFont(font)
        self.Output_label.setStyleSheet("background:none\n"
"")
        self.Output_label.setObjectName("Output_label")
        self.Labels_verticalLayout.addWidget(self.Output_label)
        self.Source_Output_horizontalLayout.addLayout(self.Labels_verticalLayout)
        self.LineEdits_verticalLayout = QtWidgets.QVBoxLayout()
        self.LineEdits_verticalLayout.setObjectName("LineEdits_verticalLayout")
        
        self.Source_lineEdit = QtWidgets.QLineEdit(self.CompilationConfig_widget)
        self.Source_lineEdit.setObjectName("Source_lineEdit")
        self.LineEdits_verticalLayout.addWidget(self.Source_lineEdit)
        self.Source_Output_horizontalLayout.addLayout(self.LineEdits_verticalLayout)
        self.Browse_verticalLayout = QtWidgets.QVBoxLayout()
        self.Browse_verticalLayout.setObjectName("Browse_verticalLayout")
        self.BrowseSource_button = QtWidgets.QToolButton(self.CompilationConfig_widget)
        self.BrowseSource_button.setObjectName("BrowseSource_button")
        self.Browse_verticalLayout.addWidget(self.BrowseSource_button)
        self.BrowseOutput_button = QtWidgets.QToolButton(self.CompilationConfig_widget)
        self.BrowseOutput_button.setObjectName("BrowseOutput_button")
        self.Browse_verticalLayout.addWidget(self.BrowseOutput_button)
        
        self.Source_Output_horizontalLayout.addLayout(self.Browse_verticalLayout)
        self.CompilationConfig_gridLayout.addLayout(self.Source_Output_horizontalLayout, 1, 0, 1, 1)
        self.Output_lineEdit = QtWidgets.QLineEdit(self.CompilationConfig_widget)
        self.Output_lineEdit.setObjectName("Output_lineEdit")
        self.Output_lineEdit.setReadOnly(True)
        self.LineEdits_verticalLayout.addWidget(self.Output_lineEdit)
        self.Machine_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Machine_horizontalLayout.setObjectName("Machine_horizontalLayout")
        self.Machine_label = QtWidgets.QLabel(self.CompilationConfig_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Machine_label.setFont(font)
        self.Machine_label.setStyleSheet("background:none")
        self.Machine_label.setObjectName("Machine_label")
        self.Machine_horizontalLayout.addWidget(self.Machine_label)
        self.Machine_comboBox = QtWidgets.QComboBox(self.CompilationConfig_widget)
        self.Machine_comboBox.setObjectName("Machine_comboBox")
        self.Machine_comboBox.addItem("")
        self.Machine_comboBox.addItem("")
        self.Machine_comboBox.addItem("")
        self.Machine_comboBox.addItem("")
        self.Machine_horizontalLayout.addWidget(self.Machine_comboBox)
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Machine_horizontalLayout.addItem(spacerItem)
        self.CompilationConfig_gridLayout.addLayout(self.Machine_horizontalLayout, 2, 0, 1, 1)
        self.Force_checkBox = QtWidgets.QCheckBox(self.CompilationConfig_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Force_checkBox.setFont(font)
        self.Force_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Force_checkBox.setObjectName("Force_checkBox")
        self.CompilationConfig_gridLayout.addWidget(self.Force_checkBox, 3, 0, 1, 1)
        self.Timeout_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Timeout_horizontalLayout.setObjectName("Timeout_horizontalLayout")
        self.Timeout_label = QtWidgets.QLabel(self.CompilationConfig_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Timeout_label.setFont(font)
        self.Timeout_label.setStyleSheet("background:none")
        self.Timeout_label.setObjectName("Timeout_label")
        self.Timeout_horizontalLayout.addWidget(self.Timeout_label)
        self.Timeout_lineEdit = QtWidgets.QLineEdit(self.CompilationConfig_widget)
        self.Timeout_lineEdit.setObjectName("Timeout_lineEdit")
        self.Timeout_horizontalLayout.addWidget(self.Timeout_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Timeout_horizontalLayout.addItem(spacerItem1)
        self.CompilationConfig_gridLayout.addLayout(self.Timeout_horizontalLayout, 4, 0, 1, 1)
        self.Done_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Done_horizontalLayout.setObjectName("Done_horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Done_horizontalLayout.addItem(spacerItem2)
        self.Done_button = QtWidgets.QPushButton(self.CompilationConfig_widget)
        self.Done_button.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.Done_button.setFont(font)
        self.Done_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(33, 188, 180);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(84, 195, 195);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(25, 154, 147);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(180, 180, 180);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"")
        self.Done_button.setObjectName("Done_button")
        self.Done_horizontalLayout.addWidget(self.Done_button)
        self.CompilationConfig_gridLayout.addLayout(self.Done_horizontalLayout, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.CompilationConfig_gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.CompilationConfig_widget, 0, 0, 1, 1)

        self.retranslateUi(CompilationConfig_Form)
        QtCore.QMetaObject.connectSlotsByName(CompilationConfig_Form)

    def retranslateUi(self, CompilationConfig_Form):
        _translate = QtCore.QCoreApplication.translate
        CompilationConfig_Form.setWindowTitle(_translate("CompilationConfig_Form", "Compilation Configuration"))
        self.Source_label.setText(_translate("CompilationConfig_Form", "Source Design Path"))
        self.Output_label.setText(_translate("CompilationConfig_Form", "Output Directory"))
        self.BrowseSource_button.setText(_translate("CompilationConfig_Form", "..."))
        self.BrowseOutput_button.setText(_translate("CompilationConfig_Form", ""))
        self.Machine_label.setText(_translate("CompilationConfig_Form", "Machine"))
        self.Machine_comboBox.setItemText(0, _translate("CompilationConfig_Form", "Auto"))
        self.Machine_comboBox.setItemText(1, _translate("CompilationConfig_Form", "egc-med-bell"))
        self.Machine_comboBox.setItemText(2, _translate("CompilationConfig_Form", "egc-med-baird"))
        self.Machine_comboBox.setItemText(3, _translate("CompilationConfig_Form", "egc-med-nozark"))
        self.Force_checkBox.setText(_translate("CompilationConfig_Form", "Force"))
        self.Timeout_label.setText(_translate("CompilationConfig_Form", "TimeOut"))
        self.Timeout_lineEdit.setPlaceholderText(_translate("CompilationConfig_Form", "0"))
        self.Done_button.setText(_translate("CompilationConfig_Form", "Done"))
        
        
        