# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DUTBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DUTConfiguration(object):
    def setupUi(self, DUTConfiguration):
        DUTConfiguration.setObjectName("DUTConfiguration")
        DUTConfiguration.resize(764, 2197)
        DUTConfiguration.setStyleSheet("\n"
"/* QFrame */\n"
"QWidget {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"background-color:none;\n"
"    color: rgb(255, 255, 255);\n"
"font-size:22px;\n"
"font:normal;\n"
"\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    background-color:#1b1d23;\n"
"    color: rgb(255, 255, 255);\n"
"    margin:10px;\n"
"    padding:5px;\n"
"font:bold 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:22px;\n"
"    font:normal; \n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(\":/icons/icons/cil-chevron-bottom.png\");\n"
"    width:15px;\n"
"    height:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* QGroupBox  */\n"
"QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 40px;\n"
"    margin-left: 20px;\n"
"margin-bottom: 40px;\n"
"    margin-right: 20px;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"}\n"
"/* LineEdit */\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"    font-size:20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* Table */\n"
"\n"
"QGroupBox\n"
"{\n"
"background-color:transparent;\n"
"\n"
"font:22px;\n"
"font:bold;\n"
"border-color:white;\n"
"}\n"
"QCheckBox\n"
"{\n"
"background-color:none;\n"
"    font-size:22px;\n"
"    font:normal; \n"
"     color:white;\n"
"}\n"
"QListWidget\n"
"{\n"
"    font-size:18px;\n"
"    font:normal; \n"
"     color:white;\n"
"    background-color: rgb(52, 59, 72);\n"
"\n"
"}")
        self.gridLayout_8 = QtWidgets.QGridLayout(DUTConfiguration)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.RecordConf_Groupbox = QtWidgets.QGroupBox(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordConf_Groupbox.sizePolicy().hasHeightForWidth())
        self.RecordConf_Groupbox.setSizePolicy(sizePolicy)
        self.RecordConf_Groupbox.setStyleSheet("")
        self.RecordConf_Groupbox.setObjectName("RecordConf_Groupbox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.RecordConf_Groupbox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RecordDir_label_2 = QtWidgets.QLabel(self.RecordConf_Groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordDir_label_2.sizePolicy().hasHeightForWidth())
        self.RecordDir_label_2.setSizePolicy(sizePolicy)
        self.RecordDir_label_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.RecordDir_label_2.setObjectName("RecordDir_label_2")
        self.horizontalLayout_4.addWidget(self.RecordDir_label_2)
        self.RecordDir_lineEdit_2 = QtWidgets.QLineEdit(self.RecordConf_Groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordDir_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.RecordDir_lineEdit_2.setSizePolicy(sizePolicy)
        self.RecordDir_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.RecordDir_lineEdit_2.setObjectName("RecordDir_lineEdit_2")
        self.horizontalLayout_4.addWidget(self.RecordDir_lineEdit_2)
        self.RecordDir_toolButton_2 = QtWidgets.QToolButton(self.RecordConf_Groupbox)
        self.RecordDir_toolButton_2.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.RecordDir_toolButton_2.setObjectName("RecordDir_toolButton_2")
        self.horizontalLayout_4.addWidget(self.RecordDir_toolButton_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.Snapshots_GroupBox = QtWidgets.QGroupBox(self.RecordConf_Groupbox)
        self.Snapshots_GroupBox.setObjectName("Snapshots_GroupBox")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Snapshots_GroupBox)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.ConfigType_Hlayout = QtWidgets.QHBoxLayout()
        self.ConfigType_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.ConfigType_Hlayout.setObjectName("ConfigType_Hlayout")
        self.ConfigType_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigType_label.sizePolicy().hasHeightForWidth())
        self.ConfigType_label.setSizePolicy(sizePolicy)
        self.ConfigType_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ConfigType_label.setObjectName("ConfigType_label")
        self.ConfigType_Hlayout.addWidget(self.ConfigType_label)
        self.ConfigType_comboBox = QtWidgets.QComboBox(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(56)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.ConfigType_comboBox.sizePolicy().hasHeightForWidth())
        self.ConfigType_comboBox.setSizePolicy(sizePolicy)
        self.ConfigType_comboBox.setAutoFillBackground(False)
        self.ConfigType_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.ConfigType_comboBox.setObjectName("ConfigType_comboBox")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_Hlayout.addWidget(self.ConfigType_comboBox)
        self.verticalLayout_12.addLayout(self.ConfigType_Hlayout)
        self.ConfigValue_Vlayout = QtWidgets.QVBoxLayout()
        self.ConfigValue_Vlayout.setObjectName("ConfigValue_Vlayout")
        self.FromConfigValue_Hlayout = QtWidgets.QHBoxLayout()
        self.FromConfigValue_Hlayout.setObjectName("FromConfigValue_Hlayout")
        self.FromConfigValue_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FromConfigValue_label.sizePolicy().hasHeightForWidth())
        self.FromConfigValue_label.setSizePolicy(sizePolicy)
        self.FromConfigValue_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.FromConfigValue_label.setObjectName("FromConfigValue_label")
        self.FromConfigValue_Hlayout.addWidget(self.FromConfigValue_label)
        self.FromConfigValue_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FromConfigValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.FromConfigValue_lineEdit.setSizePolicy(sizePolicy)
        self.FromConfigValue_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.FromConfigValue_lineEdit.setObjectName("FromConfigValue_lineEdit")
        self.FromConfigValue_Hlayout.addWidget(self.FromConfigValue_lineEdit)
        self.ConfigValue_Vlayout.addLayout(self.FromConfigValue_Hlayout)
        self.ToConfigValue_Hlayout = QtWidgets.QHBoxLayout()
        self.ToConfigValue_Hlayout.setObjectName("ToConfigValue_Hlayout")
        self.ToConfigValue_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.ToConfigValue_label.sizePolicy().hasHeightForWidth())
        self.ToConfigValue_label.setSizePolicy(sizePolicy)
        self.ToConfigValue_label.setMinimumSize(QtCore.QSize(0, 0))
        self.ToConfigValue_label.setObjectName("ToConfigValue_label")
        self.ToConfigValue_Hlayout.addWidget(self.ToConfigValue_label)
        self.ToConfigValue_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToConfigValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.ToConfigValue_lineEdit.setSizePolicy(sizePolicy)
        self.ToConfigValue_lineEdit.setObjectName("ToConfigValue_lineEdit")
        self.ToConfigValue_Hlayout.addWidget(self.ToConfigValue_lineEdit)
        self.ConfigValue_Vlayout.addLayout(self.ToConfigValue_Hlayout)
        self.verticalLayout_12.addLayout(self.ConfigValue_Vlayout)
        self.Configvalue_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Configvalue_horizontalLayout.setObjectName("Configvalue_horizontalLayout")
        self.Configvalue_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Configvalue_label.sizePolicy().hasHeightForWidth())
        self.Configvalue_label.setSizePolicy(sizePolicy)
        self.Configvalue_label.setObjectName("Configvalue_label")
        self.Configvalue_horizontalLayout.addWidget(self.Configvalue_label)
        self.Configvalue_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Configvalue_lineEdit.sizePolicy().hasHeightForWidth())
        self.Configvalue_lineEdit.setSizePolicy(sizePolicy)
        self.Configvalue_lineEdit.setObjectName("Configvalue_lineEdit")
        self.Configvalue_horizontalLayout.addWidget(self.Configvalue_lineEdit)
        self.verticalLayout_12.addLayout(self.Configvalue_horizontalLayout)
        self.ConfigValueList_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ConfigValueList_horizontalLayout.setObjectName("ConfigValueList_horizontalLayout")
        self.ConfigValueList_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigValueList_label.sizePolicy().hasHeightForWidth())
        self.ConfigValueList_label.setSizePolicy(sizePolicy)
        self.ConfigValueList_label.setObjectName("ConfigValueList_label")
        self.ConfigValueList_horizontalLayout.addWidget(self.ConfigValueList_label)
        self.ConfigValueList_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigValueList_lineEdit.sizePolicy().hasHeightForWidth())
        self.ConfigValueList_lineEdit.setSizePolicy(sizePolicy)
        self.ConfigValueList_lineEdit.setObjectName("ConfigValueList_lineEdit")
        self.ConfigValueList_horizontalLayout.addWidget(self.ConfigValueList_lineEdit)
        self.verticalLayout_12.addLayout(self.ConfigValueList_horizontalLayout)
        self.gridLayout_5.addWidget(self.Snapshots_GroupBox, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.RecordConf_Groupbox, 6, 0, 1, 1)
        self.ReplyConf_groupbox = QtWidgets.QGroupBox(DUTConfiguration)
        self.ReplyConf_groupbox.setStyleSheet("")
        self.ReplyConf_groupbox.setObjectName("ReplyConf_groupbox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.ReplyConf_groupbox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.ReplyDir_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.ReplyDir_Hlayout_2.setObjectName("ReplyDir_Hlayout_2")
        self.ReplyDir_label_2 = QtWidgets.QLabel(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplyDir_label_2.sizePolicy().hasHeightForWidth())
        self.ReplyDir_label_2.setSizePolicy(sizePolicy)
        self.ReplyDir_label_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ReplyDir_label_2.setObjectName("ReplyDir_label_2")
        self.ReplyDir_Hlayout_2.addWidget(self.ReplyDir_label_2)
        self.ReplyDir_lineEdit_2 = QtWidgets.QLineEdit(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplyDir_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.ReplyDir_lineEdit_2.setSizePolicy(sizePolicy)
        self.ReplyDir_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ReplyDir_lineEdit_2.setObjectName("ReplyDir_lineEdit_2")
        self.ReplyDir_Hlayout_2.addWidget(self.ReplyDir_lineEdit_2)
        self.ReplyDir_toolButton_2 = QtWidgets.QToolButton(self.ReplyConf_groupbox)
        self.ReplyDir_toolButton_2.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.ReplyDir_toolButton_2.setObjectName("ReplyDir_toolButton_2")
        self.ReplyDir_Hlayout_2.addWidget(self.ReplyDir_toolButton_2)
        self.verticalLayout_9.addLayout(self.ReplyDir_Hlayout_2)
        self.ReplySnapshotName_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.ReplySnapshotName_Hlayout_2.setObjectName("ReplySnapshotName_Hlayout_2")
        self.ReplySnapshotName_label_2 = QtWidgets.QLabel(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplySnapshotName_label_2.sizePolicy().hasHeightForWidth())
        self.ReplySnapshotName_label_2.setSizePolicy(sizePolicy)
        self.ReplySnapshotName_label_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ReplySnapshotName_label_2.setObjectName("ReplySnapshotName_label_2")
        self.ReplySnapshotName_Hlayout_2.addWidget(self.ReplySnapshotName_label_2)
        self.ReplySnapshotName_lineEdit_2 = QtWidgets.QLineEdit(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplySnapshotName_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.ReplySnapshotName_lineEdit_2.setSizePolicy(sizePolicy)
        self.ReplySnapshotName_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ReplySnapshotName_lineEdit_2.setObjectName("ReplySnapshotName_lineEdit_2")
        self.ReplySnapshotName_Hlayout_2.addWidget(self.ReplySnapshotName_lineEdit_2)
        self.verticalLayout_9.addLayout(self.ReplySnapshotName_Hlayout_2)
        self.gridLayout_8.addWidget(self.ReplyConf_groupbox, 7, 0, 1, 1)
        self.AVBList_Vlayout_2 = QtWidgets.QHBoxLayout()
        self.AVBList_Vlayout_2.setObjectName("AVBList_Vlayout_2")
        self.AVBList_label_2 = QtWidgets.QLabel(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AVBList_label_2.sizePolicy().hasHeightForWidth())
        self.AVBList_label_2.setSizePolicy(sizePolicy)
        self.AVBList_label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.AVBList_label_2.setStyleSheet("")
        self.AVBList_label_2.setObjectName("AVBList_label_2")
        self.AVBList_Vlayout_2.addWidget(self.AVBList_label_2)
        self.AVB_ListView_2 = QtWidgets.QListWidget(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.AVB_ListView_2.sizePolicy().hasHeightForWidth())
        self.AVB_ListView_2.setSizePolicy(sizePolicy)
        self.AVB_ListView_2.setMinimumSize(QtCore.QSize(0, 0))
        self.AVB_ListView_2.setMaximumSize(QtCore.QSize(200000, 75))
        self.AVB_ListView_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.AVB_ListView_2.setBaseSize(QtCore.QSize(0, 0))
        self.AVB_ListView_2.setAutoFillBackground(False)
        self.AVB_ListView_2.setStyleSheet("QListWidget:Item\n"
"{\n"
"font-size:10px;\n"
"}\n"
"\n"
"QListWidget:Icon\n"
"{\n"
"size:15px;\n"
"\n"
"}\n"
"\n"
"QListWidget\n"
"{\n"
"padding:5px;\n"
"}")
        self.AVB_ListView_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AVB_ListView_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AVB_ListView_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.AVB_ListView_2.setAutoScroll(False)
        self.AVB_ListView_2.setAutoScrollMargin(0)
        self.AVB_ListView_2.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.AVB_ListView_2.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.AVB_ListView_2.setAlternatingRowColors(False)
        self.AVB_ListView_2.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.AVB_ListView_2.setIconSize(QtCore.QSize(0, 0))
        self.AVB_ListView_2.setTextElideMode(QtCore.Qt.ElideNone)
        self.AVB_ListView_2.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.AVB_ListView_2.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.AVB_ListView_2.setMovement(QtWidgets.QListView.Static)
        self.AVB_ListView_2.setFlow(QtWidgets.QListView.LeftToRight)
        self.AVB_ListView_2.setProperty("isWrapping", True)
        self.AVB_ListView_2.setResizeMode(QtWidgets.QListView.Adjust)
        self.AVB_ListView_2.setLayoutMode(QtWidgets.QListView.Batched)
        self.AVB_ListView_2.setGridSize(QtCore.QSize(52, 32))
        self.AVB_ListView_2.setViewMode(QtWidgets.QListView.ListMode)
        self.AVB_ListView_2.setModelColumn(0)
        self.AVB_ListView_2.setUniformItemSizes(True)
        self.AVB_ListView_2.setBatchSize(7)
        self.AVB_ListView_2.setWordWrap(True)
        self.AVB_ListView_2.setSelectionRectVisible(False)
        self.AVB_ListView_2.setObjectName("AVB_ListView_2")
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView_2.addItem(item)
        
        self.AVBList_Vlayout_2.addWidget(self.AVB_ListView_2)
        self.gridLayout_8.addLayout(self.AVBList_Vlayout_2, 4, 0, 1, 1)
        self.TermianteDPI_checkBox = QtWidgets.QCheckBox(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TermianteDPI_checkBox.sizePolicy().hasHeightForWidth())
        self.TermianteDPI_checkBox.setSizePolicy(sizePolicy)
        self.TermianteDPI_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.TermianteDPI_checkBox.setStyleSheet("")
        self.TermianteDPI_checkBox.setObjectName("TermianteDPI_checkBox")
        self.gridLayout_8.addWidget(self.TermianteDPI_checkBox, 2, 0, 1, 1)
        self.DPIConf_groupbox = QtWidgets.QGroupBox(DUTConfiguration)
        self.DPIConf_groupbox.setStyleSheet("")
        self.DPIConf_groupbox.setObjectName("DPIConf_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.DPIConf_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.DPIAdditionalArg_groupBox_2 = QtWidgets.QGroupBox(self.DPIConf_groupbox)
        self.DPIAdditionalArg_groupBox_2.setObjectName("DPIAdditionalArg_groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DPIAdditionalArg_groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AddEnvLayout_6 = QtWidgets.QHBoxLayout()
        self.AddEnvLayout_6.setObjectName("AddEnvLayout_6")
        spacerItem = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddEnvLayout_6.addItem(spacerItem)
        self.AddEnv_2 = QtWidgets.QPushButton(self.DPIAdditionalArg_groupBox_2)
        self.AddEnv_2.setMinimumSize(QtCore.QSize(111, 54))
        self.AddEnv_2.setStyleSheet("    background-color: rgb(33, 188, 180);\n"
"")
        self.AddEnv_2.setObjectName("AddEnv_2")
        self.AddEnvLayout_6.addWidget(self.AddEnv_2)
        self.gridLayout_3.addLayout(self.AddEnvLayout_6, 3, 0, 1, 1)
        self.DeleteEnvLayout_DPI = QtWidgets.QHBoxLayout()
        self.DeleteEnvLayout_DPI.setObjectName("DeleteEnvLayout_DPI")
        spacerItem1 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DeleteEnvLayout_DPI.addItem(spacerItem1)
        self.DeleteEnv_DPI = QtWidgets.QPushButton(self.DPIAdditionalArg_groupBox_2)
        self.DeleteEnv_DPI.setMinimumSize(QtCore.QSize(111, 54))
        self.DeleteEnv_DPI.setStyleSheet("    background-color: red;\n"
"")
        self.DeleteEnv_DPI.setObjectName("DeleteEnv_DPI")
        self.DeleteEnvLayout_DPI.addWidget(self.DeleteEnv_DPI)
        self.gridLayout_3.addLayout(self.DeleteEnvLayout_DPI, 4, 0, 1, 1)
        self.EnvVarValue_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.EnvVarValue_Hlayout_2.setObjectName("EnvVarValue_Hlayout_2")
        self.EnvVarValue_label_2 = QtWidgets.QLabel(self.DPIAdditionalArg_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarValue_label_2.sizePolicy().hasHeightForWidth())
        self.EnvVarValue_label_2.setSizePolicy(sizePolicy)
        self.EnvVarValue_label_2.setObjectName("EnvVarValue_label_2")
        self.EnvVarValue_Hlayout_2.addWidget(self.EnvVarValue_label_2)
        self.EnvVarValue_lineEdit_2 = QtWidgets.QLineEdit(self.DPIAdditionalArg_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarValue_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.EnvVarValue_lineEdit_2.setSizePolicy(sizePolicy)
        self.EnvVarValue_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.EnvVarValue_lineEdit_2.setObjectName("EnvVarValue_lineEdit_2")
        self.EnvVarValue_Hlayout_2.addWidget(self.EnvVarValue_lineEdit_2)
        self.gridLayout_3.addLayout(self.EnvVarValue_Hlayout_2, 1, 0, 1, 1)
        self.DPIAdditionalEnvValues_2 = QtWidgets.QTextBrowser(self.DPIAdditionalArg_groupBox_2)
        self.DPIAdditionalEnvValues_2.setStyleSheet("    border:none;\n"
"")
        self.DPIAdditionalEnvValues_2.setObjectName("DPIAdditionalEnvValues_2")
        self.gridLayout_3.addWidget(self.DPIAdditionalEnvValues_2, 2, 0, 1, 1)
        self.EnvVarName_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.EnvVarName_Hlayout_2.setObjectName("EnvVarName_Hlayout_2")
        self.EnvVarName_label_2 = QtWidgets.QLabel(self.DPIAdditionalArg_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarName_label_2.sizePolicy().hasHeightForWidth())
        self.EnvVarName_label_2.setSizePolicy(sizePolicy)
        self.EnvVarName_label_2.setObjectName("EnvVarName_label_2")
        self.EnvVarName_Hlayout_2.addWidget(self.EnvVarName_label_2)
        self.EnvVarName_HSpacer_mid_lineEdit_2 = QtWidgets.QLineEdit(self.DPIAdditionalArg_groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarName_HSpacer_mid_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.EnvVarName_HSpacer_mid_lineEdit_2.setSizePolicy(sizePolicy)
        self.EnvVarName_HSpacer_mid_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.EnvVarName_HSpacer_mid_lineEdit_2.setObjectName("EnvVarName_HSpacer_mid_lineEdit_2")
        self.EnvVarName_Hlayout_2.addWidget(self.EnvVarName_HSpacer_mid_lineEdit_2)
        self.gridLayout_3.addLayout(self.EnvVarName_Hlayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.DPIAdditionalArg_groupBox_2, 3, 0, 1, 1)
        self.DPIAdditionalArgGroupBox_2 = QtWidgets.QGroupBox(self.DPIConf_groupbox)
        self.DPIAdditionalArgGroupBox_2.setStyleSheet("")
        self.DPIAdditionalArgGroupBox_2.setObjectName("DPIAdditionalArgGroupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.DPIAdditionalArgGroupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DeleteArgLayout_DPI = QtWidgets.QHBoxLayout()
        self.DeleteArgLayout_DPI.setObjectName("DeleteArgLayout_DPI")
        spacerItem2 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DeleteArgLayout_DPI.addItem(spacerItem2)
        self.DeleteArgButton_DPI = QtWidgets.QPushButton(self.DPIAdditionalArgGroupBox_2)
        self.DeleteArgButton_DPI.setMinimumSize(QtCore.QSize(111, 54))
        self.DeleteArgButton_DPI.setStyleSheet("    background-color: red;\n"
"")
        self.DeleteArgButton_DPI.setObjectName("DeleteArgButton_DPI")
        self.DeleteArgLayout_DPI.addWidget(self.DeleteArgButton_DPI)
        self.gridLayout_2.addLayout(self.DeleteArgLayout_DPI, 4, 0, 1, 1)
        self.ArgName_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.ArgName_Hlayout_2.setObjectName("ArgName_Hlayout_2")
        self.ArgName_label_2 = QtWidgets.QLabel(self.DPIAdditionalArgGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgName_label_2.sizePolicy().hasHeightForWidth())
        self.ArgName_label_2.setSizePolicy(sizePolicy)
        self.ArgName_label_2.setObjectName("ArgName_label_2")
        self.ArgName_Hlayout_2.addWidget(self.ArgName_label_2)
        self.ArgName_HSpacer_mid_lineEdit_2 = QtWidgets.QLineEdit(self.DPIAdditionalArgGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgName_HSpacer_mid_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.ArgName_HSpacer_mid_lineEdit_2.setSizePolicy(sizePolicy)
        self.ArgName_HSpacer_mid_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ArgName_HSpacer_mid_lineEdit_2.setObjectName("ArgName_HSpacer_mid_lineEdit_2")
        self.ArgName_Hlayout_2.addWidget(self.ArgName_HSpacer_mid_lineEdit_2)
        self.gridLayout_2.addLayout(self.ArgName_Hlayout_2, 0, 0, 1, 1)
        self.DPIAdditionalArg_2 = QtWidgets.QTextBrowser(self.DPIAdditionalArgGroupBox_2)
        self.DPIAdditionalArg_2.setStyleSheet("border:none;")
        self.DPIAdditionalArg_2.setObjectName("DPIAdditionalArg_2")
        self.gridLayout_2.addWidget(self.DPIAdditionalArg_2, 2, 0, 1, 1)
        self.ArgValue_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.ArgValue_Hlayout_2.setObjectName("ArgValue_Hlayout_2")
        self.ArgValue_label_2 = QtWidgets.QLabel(self.DPIAdditionalArgGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgValue_label_2.sizePolicy().hasHeightForWidth())
        self.ArgValue_label_2.setSizePolicy(sizePolicy)
        self.ArgValue_label_2.setObjectName("ArgValue_label_2")
        self.ArgValue_Hlayout_2.addWidget(self.ArgValue_label_2)
        self.ArgValue_lineEdit_2 = QtWidgets.QLineEdit(self.DPIAdditionalArgGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgValue_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.ArgValue_lineEdit_2.setSizePolicy(sizePolicy)
        self.ArgValue_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ArgValue_lineEdit_2.setObjectName("ArgValue_lineEdit_2")
        self.ArgValue_Hlayout_2.addWidget(self.ArgValue_lineEdit_2)
        self.gridLayout_2.addLayout(self.ArgValue_Hlayout_2, 1, 0, 1, 1)
        self.AddArgLayout_5 = QtWidgets.QHBoxLayout()
        self.AddArgLayout_5.setObjectName("AddArgLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddArgLayout_5.addItem(spacerItem3)
        self.AddArgButton_2 = QtWidgets.QPushButton(self.DPIAdditionalArgGroupBox_2)
        self.AddArgButton_2.setMinimumSize(QtCore.QSize(111, 54))
        self.AddArgButton_2.setStyleSheet("    background-color: rgb(33, 188, 180);\n"
"")
        self.AddArgButton_2.setObjectName("AddArgButton_2")
        self.AddArgLayout_5.addWidget(self.AddArgButton_2)
        self.gridLayout_2.addLayout(self.AddArgLayout_5, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.DPIAdditionalArgGroupBox_2, 2, 0, 1, 1)
        self.CustomComConf_checkbox_2 = QtWidgets.QCheckBox(self.DPIConf_groupbox)
        self.CustomComConf_checkbox_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.CustomComConf_checkbox_2.setObjectName("CustomComConf_checkbox_2")
        self.gridLayout.addWidget(self.CustomComConf_checkbox_2, 4, 0, 1, 1)
        self.DPILaunchType_HLayout_2 = QtWidgets.QHBoxLayout()
        self.DPILaunchType_HLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.DPILaunchType_HLayout_2.setObjectName("DPILaunchType_HLayout_2")
        self.DPILaunchType_label_2 = QtWidgets.QLabel(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.DPILaunchType_label_2.sizePolicy().hasHeightForWidth())
        self.DPILaunchType_label_2.setSizePolicy(sizePolicy)
        self.DPILaunchType_label_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DPILaunchType_label_2.setObjectName("DPILaunchType_label_2")
        self.DPILaunchType_HLayout_2.addWidget(self.DPILaunchType_label_2)
        self.DPILaunchType_comboBox_2 = QtWidgets.QComboBox(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchType_comboBox_2.sizePolicy().hasHeightForWidth())
        self.DPILaunchType_comboBox_2.setSizePolicy(sizePolicy)
        self.DPILaunchType_comboBox_2.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.DPILaunchType_comboBox_2.setObjectName("DPILaunchType_comboBox_2")
        self.DPILaunchType_comboBox_2.addItem("")
        self.DPILaunchType_comboBox_2.addItem("")
        self.DPILaunchType_comboBox_2.addItem("")
        self.DPILaunchType_comboBox_2.addItem("")
        self.DPILaunchType_HLayout_2.addWidget(self.DPILaunchType_comboBox_2)
        self.gridLayout.addLayout(self.DPILaunchType_HLayout_2, 1, 0, 1, 1)
        self.DPILaunchModeHLayout_2 = QtWidgets.QHBoxLayout()
        self.DPILaunchModeHLayout_2.setObjectName("DPILaunchModeHLayout_2")
        self.DPILaunchMode_label_2 = QtWidgets.QLabel(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchMode_label_2.sizePolicy().hasHeightForWidth())
        self.DPILaunchMode_label_2.setSizePolicy(sizePolicy)
        self.DPILaunchMode_label_2.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DPILaunchMode_label_2.setObjectName("DPILaunchMode_label_2")
        self.DPILaunchModeHLayout_2.addWidget(self.DPILaunchMode_label_2)
        self.DPILaunchMode_lineEdit_2 = QtWidgets.QLineEdit(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchMode_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.DPILaunchMode_lineEdit_2.setSizePolicy(sizePolicy)
        self.DPILaunchMode_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.DPILaunchMode_lineEdit_2.setObjectName("DPILaunchMode_lineEdit_2")
        self.DPILaunchModeHLayout_2.addWidget(self.DPILaunchMode_lineEdit_2)
        self.gridLayout.addLayout(self.DPILaunchModeHLayout_2, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.DPIConf_groupbox, 8, 0, 1, 1)
        self.LaunchDPI_checkBox = QtWidgets.QCheckBox(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LaunchDPI_checkBox.sizePolicy().hasHeightForWidth())
        self.LaunchDPI_checkBox.setSizePolicy(sizePolicy)
        self.LaunchDPI_checkBox.setStyleSheet("font-size:22px;\n"
"font:normal;\n"
"background:none;")
        self.LaunchDPI_checkBox.setObjectName("LaunchDPI_checkBox")
        self.gridLayout_8.addWidget(self.LaunchDPI_checkBox, 3, 0, 1, 1)
        self.DesignPath_Hlayout_2 = QtWidgets.QHBoxLayout()
        self.DesignPath_Hlayout_2.setObjectName("DesignPath_Hlayout_2")
        self.DesignPath_label_2 = QtWidgets.QLabel(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesignPath_label_2.sizePolicy().hasHeightForWidth())
        self.DesignPath_label_2.setSizePolicy(sizePolicy)
        self.DesignPath_label_2.setStyleSheet("font-size:22px;\n"
"font:normal;\n"
"")
        self.DesignPath_label_2.setObjectName("DesignPath_label_2")
        self.DesignPath_Hlayout_2.addWidget(self.DesignPath_label_2)
        self.DesignPath_lineEdit_2 = QtWidgets.QLineEdit(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesignPath_lineEdit_2.sizePolicy().hasHeightForWidth())
        self.DesignPath_lineEdit_2.setSizePolicy(sizePolicy)
        self.DesignPath_lineEdit_2.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.DesignPath_lineEdit_2.setObjectName("DesignPath_lineEdit_2")
        self.DesignPath_Hlayout_2.addWidget(self.DesignPath_lineEdit_2)
        self.DesignPath_toolButton_2 = QtWidgets.QToolButton(DUTConfiguration)
        self.DesignPath_toolButton_2.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.DesignPath_toolButton_2.setObjectName("DesignPath_toolButton_2")
        self.DesignPath_Hlayout_2.addWidget(self.DesignPath_toolButton_2)
        self.gridLayout_8.addLayout(self.DesignPath_Hlayout_2, 5, 0, 1, 1)
        self.TerminateDPIOnError_checkBox = QtWidgets.QCheckBox(DUTConfiguration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.TerminateDPIOnError_checkBox.sizePolicy().hasHeightForWidth())
        self.TerminateDPIOnError_checkBox.setSizePolicy(sizePolicy)
        self.TerminateDPIOnError_checkBox.setStyleSheet("background-color:none;")
        self.TerminateDPIOnError_checkBox.setObjectName("TerminateDPIOnError_checkBox")
        self.gridLayout_8.addWidget(self.TerminateDPIOnError_checkBox, 1, 0, 1, 1)
        self.Delete_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Delete_horizontalLayout.setObjectName("Delete_horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Delete_horizontalLayout.addItem(spacerItem4)
        self.Dut_pushButton = QtWidgets.QPushButton(DUTConfiguration)
        self.Dut_pushButton.setStyleSheet("background:none;\n"
"")
        self.Dut_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dut_pushButton.setIcon(icon)
        self.Dut_pushButton.setIconSize(QtCore.QSize(24, 31))
        self.Dut_pushButton.setObjectName("Dut_pushButton")
        self.Delete_horizontalLayout.addWidget(self.Dut_pushButton)
        self.gridLayout_8.addLayout(self.Delete_horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(DUTConfiguration)
        self.AVB_ListView_2.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(DUTConfiguration)
    
    
    
    def retranslateUi(self, DUTConfiguration):
        _translate = QtCore.QCoreApplication.translate
        DUTConfiguration.setWindowTitle(_translate("DUTConfiguration", "GroupBox"))
        DUTConfiguration.setTitle(_translate("DUTConfiguration", "DUT Configuration"))
        self.RecordConf_Groupbox.setTitle(_translate("DUTConfiguration", "Record Configurations"))
        self.RecordDir_label_2.setText(_translate("DUTConfiguration", "Record Directory"))
        self.RecordDir_toolButton_2.setText(_translate("DUTConfiguration", "..."))
        self.Snapshots_GroupBox.setTitle(_translate("DUTConfiguration", "SnapShots Number"))
        self.ConfigType_label.setText(_translate("DUTConfiguration", "Config Type"))
        self.ConfigType_comboBox.setItemText(0, _translate("DUTConfiguration", "Range"))
        self.ConfigType_comboBox.setItemText(1, _translate("DUTConfiguration", "List"))
        self.ConfigType_comboBox.setItemText(2, _translate("DUTConfiguration", "Value"))
        self.FromConfigValue_label.setText(_translate("DUTConfiguration", "From"))
        self.ToConfigValue_label.setText(_translate("DUTConfiguration", "To"))
        self.Configvalue_label.setText(_translate("DUTConfiguration", "Value"))
        self.ConfigValueList_label.setText(_translate("DUTConfiguration", "Value"))
        self.ReplyConf_groupbox.setTitle(_translate("DUTConfiguration", "Reply Configurations"))
        self.ReplyDir_label_2.setText(_translate("DUTConfiguration", "Reply Directory"))
        self.ReplyDir_toolButton_2.setText(_translate("DUTConfiguration", "..."))
        self.ReplySnapshotName_label_2.setText(_translate("DUTConfiguration", "Replay Snapshot Name"))
        self.AVBList_label_2.setText(_translate("DUTConfiguration", "AVB List"))
        __sortingEnabled = self.AVB_ListView_2.isSortingEnabled()
        self.AVB_ListView_2.setSortingEnabled(False)
        item = self.AVB_ListView_2.item(0)
        item.setText(_translate("DUTConfiguration", "0"))
        item = self.AVB_ListView_2.item(1)
        item.setText(_translate("DUTConfiguration", "1"))
        item = self.AVB_ListView_2.item(2)
        item.setText(_translate("DUTConfiguration", "2"))
        item = self.AVB_ListView_2.item(3)
        item.setText(_translate("DUTConfiguration", "3"))
        item = self.AVB_ListView_2.item(4)
        item.setText(_translate("DUTConfiguration", "4"))
        item = self.AVB_ListView_2.item(5)
        item.setText(_translate("DUTConfiguration", "5"))
        item = self.AVB_ListView_2.item(6)
        item.setText(_translate("DUTConfiguration", "6"))
        item = self.AVB_ListView_2.item(7)
        item.setText(_translate("DUTConfiguration", "7"))
        item = self.AVB_ListView_2.item(8)
        item.setText(_translate("DUTConfiguration", "8"))
        item = self.AVB_ListView_2.item(9)
        item.setText(_translate("DUTConfiguration", "9"))
        item = self.AVB_ListView_2.item(10)
        item.setText(_translate("DUTConfiguration", "10"))
        item = self.AVB_ListView_2.item(11)
        item.setText(_translate("DUTConfiguration", "11"))
        item = self.AVB_ListView_2.item(12)
        item.setText(_translate("DUTConfiguration", "13"))
        item = self.AVB_ListView_2.item(13)
        item.setText(_translate("DUTConfiguration", "14"))
        item = self.AVB_ListView_2.item(14)
        item.setText(_translate("DUTConfiguration", "15"))
        self.AVB_ListView_2.setSortingEnabled(__sortingEnabled)
        #self.AVB_ListView_2.itemChanged.connect(self.itemChanged)
        self.TermianteDPI_checkBox.setText(_translate("DUTConfiguration", "  Terminate DPI"))
        self.DPIConf_groupbox.setTitle(_translate("DUTConfiguration", "DPI Configurations"))
        self.DPIAdditionalArg_groupBox_2.setTitle(_translate("DUTConfiguration", "DPI Additional Env Variables"))
        self.AddEnv_2.setText(_translate("DUTConfiguration", "Add"))
        self.DeleteEnv_DPI.setText(_translate("DUTConfiguration", "Delete"))
        self.EnvVarValue_label_2.setText(_translate("DUTConfiguration", "Variable Value"))
        self.EnvVarName_label_2.setText(_translate("DUTConfiguration", "Variable Key"))
        self.DPIAdditionalArgGroupBox_2.setTitle(_translate("DUTConfiguration", "DPI Additional Arguments"))
        self.DeleteArgButton_DPI.setText(_translate("DUTConfiguration", "Delete"))
        self.ArgName_label_2.setText(_translate("DUTConfiguration", "Argument Key"))
        self.ArgValue_label_2.setText(_translate("DUTConfiguration", "Argument Value"))
        self.AddArgButton_2.setText(_translate("DUTConfiguration", "Add"))
        self.CustomComConf_checkbox_2.setText(_translate("DUTConfiguration", "Use Custom Comodels Config"))
        self.DPILaunchType_label_2.setText(_translate("DUTConfiguration", "DPI Launch Type"))
        self.DPILaunchType_comboBox_2.setItemText(0, _translate("DUTConfiguration", "Emulation"))
        self.DPILaunchType_comboBox_2.setItemText(1, _translate("DUTConfiguration", "Simulation"))
        self.DPILaunchType_comboBox_2.setItemText(2, _translate("DUTConfiguration", "Emulation_Velclkgen"))
        self.DPILaunchType_comboBox_2.setItemText(3, _translate("DUTConfiguration", "Simulation_Velclkgen"))
        self.DPILaunchMode_label_2.setText(_translate("DUTConfiguration", "DPI Launch Mode"))
        self.LaunchDPI_checkBox.setText(_translate("DUTConfiguration", "  Launch DPI"))
        self.TerminateDPIOnError_checkBox.setText(_translate("DUTConfiguration", "  Terminate DPI on Error"))
        self.DesignPath_label_2.setText(_translate("DUTConfiguration", "Design Path"))
        self.DesignPath_toolButton_2.setText(_translate("DUTConfiguration", "..."))
        
        
#     def itemChanged(self):
#         self.collect_data()
       