# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens diploma\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\RunningConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RunningConfiguration(object):
    def setupUi(self, RunningConfiguration):
        RunningConfiguration.setObjectName("RunningConfiguration")
        RunningConfiguration.resize(654, 356)
        RunningConfiguration.setStyleSheet("QWidget{\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 11pt;\n"
"}\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 11pt;\n"
"\n"
"}\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* QGroupBox  */\n"
"QGroupBox{\n"
"    margin-top: 10px;\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"}\n"
"QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 12pt;\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(RunningConfiguration)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(RunningConfiguration)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QWidget{\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"QCheckBox{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 11pt;\n"
"}\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 11pt;\n"
"\n"
"}\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* QGroupBox  */\n"
"QGroupBox{\n"
"    margin-top: 10px;\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"}\n"
"QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 12pt;\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"    font-style:bold;\n"
"\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    background-color: rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.delete_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.delete_pushButton.setStyleSheet("background:none;")
        self.delete_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/frontend/IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_pushButton.setIcon(icon)
        self.delete_pushButton.setIconSize(QtCore.QSize(31, 25))
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.horizontalLayout.addWidget(self.delete_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.ScriptPath_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ScriptPath_horizontalLayout.setSpacing(0)
        self.ScriptPath_horizontalLayout.setObjectName("ScriptPath_horizontalLayout")
        self.ScriptPath_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.ScriptPath_label.setFont(font)
        self.ScriptPath_label.setLineWidth(0)
        self.ScriptPath_label.setObjectName("ScriptPath_label")
        self.ScriptPath_horizontalLayout.addWidget(self.ScriptPath_label)
        self.ScriptPath_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.ScriptPath_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ScriptPath_lineEdit.setStyleSheet("")
        self.ScriptPath_lineEdit.setObjectName("ScriptPath_lineEdit")
        self.ScriptPath_horizontalLayout.addWidget(self.ScriptPath_lineEdit)
        self.BrowseScriptPath_button = QtWidgets.QToolButton(self.groupBox)
        self.BrowseScriptPath_button.setStyleSheet("QToolButton {\n"
"    border: none; /* Remove border */\n"
"    background-color: transparent; /* Set background color to transparent */\n"
"}\n"
"\n"
"QToolButton::icon {\n"
"    background-color: transparent; /* Set icon background color to transparent */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BrowseScriptPath_button.setIcon(icon1)
        self.BrowseScriptPath_button.setObjectName("BrowseScriptPath_button")
        self.ScriptPath_horizontalLayout.addWidget(self.BrowseScriptPath_button)
        self.verticalLayout_2.addLayout(self.ScriptPath_horizontalLayout)
        self.RunC_2 = QtWidgets.QCheckBox(self.groupBox)
        self.RunC_2.setObjectName("RunC_2")
        self.verticalLayout_2.addWidget(self.RunC_2)
        self.ErrorType_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ErrorType_horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.ErrorType_horizontalLayout.setObjectName("ErrorType_horizontalLayout")
        self.ErrorL_2 = QtWidgets.QLabel(self.groupBox)
        self.ErrorL_2.setObjectName("ErrorL_2")
        self.ErrorType_horizontalLayout.addWidget(self.ErrorL_2)
        self.ErrorC_2 = QtWidgets.QComboBox(self.groupBox)
        self.ErrorC_2.setObjectName("ErrorC_2")
        self.ErrorC_2.addItem("")
        self.ErrorC_2.addItem("")
        self.ErrorC_2.addItem("")
        self.ErrorType_horizontalLayout.addWidget(self.ErrorC_2)
        self.ErrorConf_2 = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(88)
        sizePolicy.setHeightForWidth(self.ErrorConf_2.sizePolicy().hasHeightForWidth())
        self.ErrorConf_2.setSizePolicy(sizePolicy)
        self.ErrorConf_2.setMinimumSize(QtCore.QSize(0, 30))
        self.ErrorConf_2.setObjectName("ErrorConf_2")
        self.ErrorType_horizontalLayout.addWidget(self.ErrorConf_2)
        self.verticalLayout_2.addLayout(self.ErrorType_horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(RunningConfiguration)
        QtCore.QMetaObject.connectSlotsByName(RunningConfiguration)

    def retranslateUi(self, RunningConfiguration):
        _translate = QtCore.QCoreApplication.translate
        RunningConfiguration.setWindowTitle(_translate("RunningConfiguration", "Form"))
        self.groupBox.setTitle(_translate("RunningConfiguration", "Running Configuration 1"))
        self.ScriptPath_label.setText(_translate("RunningConfiguration", "Script Path"))
        self.BrowseScriptPath_button.setText(_translate("RunningConfiguration", "..."))
        self.RunC_2.setText(_translate("RunningConfiguration", "Run Script"))
        self.ErrorL_2.setText(_translate("RunningConfiguration", "Error Type"))
        self.ErrorC_2.setItemText(0, _translate("RunningConfiguration", "Mismatch"))
        self.ErrorC_2.setItemText(1, _translate("RunningConfiguration", "Crash"))
        self.ErrorC_2.setItemText(2, _translate("RunningConfiguration", "Hang"))
        self.ErrorConf_2.setText(_translate("RunningConfiguration", "Error Configuration"))
