import time
print("Executing script 1.1")
time.sleep(30)
print("Executing script 1.2")
# time.sleep(30)
# print("Executing script 1.3")
# time.sleep(30)
# print("Executing script 1.4")
# time.sleep(30)
# print("Executing script 1.5")
# time.sleep(30)
# print("Executing script 1.6")
# time.sleep(30)