# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens Software Diploma\Anomalies Tracker\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\ComodelsConfigBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComodelsConfigBox(object):
    def setupUi(self, ComodelsConfigBox):
        ComodelsConfigBox.setObjectName("ComodelsConfigBox")
        ComodelsConfigBox.resize(638, 0)
        ComodelsConfigBox.setStyleSheet("QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 10px;\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"font:22px;\n"
"font:bold;\n"
"border-color:white;\n"
"}\n"
"")
        ComodelsConfigBox.setTitle("")
        self.gridLayout = QtWidgets.QGridLayout(ComodelsConfigBox)
        self.gridLayout.setObjectName("gridLayout")
        self.HostName_Hlayout = QtWidgets.QHBoxLayout()
        self.HostName_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.HostName_Hlayout.setObjectName("HostName_Hlayout")
        spacerItem = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem)
        self.HostName_HSpacer_label = QtWidgets.QLabel(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostName_HSpacer_label.sizePolicy().hasHeightForWidth())
        self.HostName_HSpacer_label.setSizePolicy(sizePolicy)
        self.HostName_HSpacer_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.HostName_HSpacer_label.setObjectName("HostName_HSpacer_label")
        self.HostName_Hlayout.addWidget(self.HostName_HSpacer_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem1)
        self.HostName_comboBox = QtWidgets.QComboBox(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HostName_comboBox.sizePolicy().hasHeightForWidth())
        self.HostName_comboBox.setSizePolicy(sizePolicy)
        self.HostName_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.HostName_comboBox.setObjectName("HostName_comboBox")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_comboBox.addItem("")
        self.HostName_Hlayout.addWidget(self.HostName_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HostName_Hlayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.HostName_Hlayout, 0, 0, 1, 1)
        self.DomainId_Hlayout = QtWidgets.QHBoxLayout()
        self.DomainId_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.DomainId_Hlayout.setObjectName("DomainId_Hlayout")
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem3)
        self.DomainId_HSpacer_label = QtWidgets.QLabel(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DomainId_HSpacer_label.sizePolicy().hasHeightForWidth())
        self.DomainId_HSpacer_label.setSizePolicy(sizePolicy)
        self.DomainId_HSpacer_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DomainId_HSpacer_label.setObjectName("DomainId_HSpacer_label")
        self.DomainId_Hlayout.addWidget(self.DomainId_HSpacer_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem4)
        self.DomainId_comboBox = QtWidgets.QComboBox(ComodelsConfigBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DomainId_comboBox.sizePolicy().hasHeightForWidth())
        self.DomainId_comboBox.setSizePolicy(sizePolicy)
        self.DomainId_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.DomainId_comboBox.setObjectName("DomainId_comboBox")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_comboBox.addItem("")
        self.DomainId_Hlayout.addWidget(self.DomainId_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DomainId_Hlayout.addItem(spacerItem5)
        self.gridLayout.addLayout(self.DomainId_Hlayout, 1, 0, 1, 1)

        self.retranslateUi(ComodelsConfigBox)
        QtCore.QMetaObject.connectSlotsByName(ComodelsConfigBox)

    def retranslateUi(self, ComodelsConfigBox):
        _translate = QtCore.QCoreApplication.translate
        ComodelsConfigBox.setWindowTitle(_translate("ComodelsConfigBox", "GroupBox"))
        self.HostName_HSpacer_label.setText(_translate("ComodelsConfigBox", "Host Name"))
        self.HostName_comboBox.setItemText(0, _translate("ComodelsConfigBox", "Auto"))
        self.HostName_comboBox.setItemText(1, _translate("ComodelsConfigBox", "egc-med-bell"))
        self.HostName_comboBox.setItemText(2, _translate("ComodelsConfigBox", "egc-med-baird"))
        self.HostName_comboBox.setItemText(3, _translate("ComodelsConfigBox", "egc-med-nozark"))
        self.DomainId_HSpacer_label.setText(_translate("ComodelsConfigBox", "Domain Id"))
        self.DomainId_comboBox.setItemText(0, _translate("ComodelsConfigBox", "0"))
        self.DomainId_comboBox.setItemText(1, _translate("ComodelsConfigBox", "1"))
        self.DomainId_comboBox.setItemText(2, _translate("ComodelsConfigBox", "2"))
        self.DomainId_comboBox.setItemText(3, _translate("ComodelsConfigBox", "3"))
