# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens Software Diploma\Anomalies Tracker\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\CustomComodelsConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomComodelsConfig_Form(object):
    def setupUi(self, CustomComodelsConfig_Form):
        CustomComodelsConfig_Form.setObjectName("CustomComodelsConfig_Form")
        CustomComodelsConfig_Form.resize(524, 418)
        CustomComodelsConfig_Form.setStyleSheet("/* QFrame */\n"
"QWidget {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"background-color:none;\n"
"    color: rgb(255, 255, 255);\n"
"font-size:22px;\n"
"font:normal;\n"
"}\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:22px;\n"
"    font:normal; \n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(\":/icons/icons/cil-chevron-bottom.png\");\n"
"    width:15px;\n"
"    height:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    background-color:#1b1d23;\n"
"    color: rgb(255, 255, 255);\n"
"    margin:10px;\n"
"    padding:5px;\n"
"font:bold 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    color: white;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 10px;\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"font:22px;\n"
"font:bold;\n"
"border-color:white;\n"
"}\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CustomComodelsConfig_Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CustomComodConf_groupBox = QtWidgets.QGroupBox(CustomComodelsConfig_Form)
        self.CustomComodConf_groupBox.setObjectName("CustomComodConf_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.CustomComodConf_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ConfigVLayout = QtWidgets.QVBoxLayout()
        self.ConfigVLayout.setObjectName("ConfigVLayout")
        self.gridLayout.addLayout(self.ConfigVLayout, 1, 0, 1, 1)
        self.CustomComodelsAdd_Hlayout = QtWidgets.QHBoxLayout()
        self.CustomComodelsAdd_Hlayout.setContentsMargins(-1, 0, -1, 0)
        self.CustomComodelsAdd_Hlayout.setSpacing(0)
        self.CustomComodelsAdd_Hlayout.setObjectName("CustomComodelsAdd_Hlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CustomComodelsAdd_Hlayout.addItem(spacerItem)
        self.CustomComodelsAdd_PushButton = QtWidgets.QPushButton(self.CustomComodConf_groupBox)
        self.CustomComodelsAdd_PushButton.setStyleSheet("    background-color:#1b1d23;\n"
"padding-right:10px;\n"
"padding-left:10px;\n"
"")
        self.CustomComodelsAdd_PushButton.setObjectName("CustomComodelsAdd_PushButton")
        self.CustomComodelsAdd_Hlayout.addWidget(self.CustomComodelsAdd_PushButton)
        self.gridLayout.addLayout(self.CustomComodelsAdd_Hlayout, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.CustomComodConf_groupBox)

        self.retranslateUi(CustomComodelsConfig_Form)
        QtCore.QMetaObject.connectSlotsByName(CustomComodelsConfig_Form)

    def retranslateUi(self, CustomComodelsConfig_Form):
        _translate = QtCore.QCoreApplication.translate
        CustomComodelsConfig_Form.setWindowTitle(_translate("CustomComodelsConfig_Form", "Form"))
        self.CustomComodConf_groupBox.setTitle(_translate("CustomComodelsConfig_Form", "Custom Comodels config"))
        self.CustomComodelsAdd_PushButton.setText(_translate("CustomComodelsConfig_Form", "+"))
