# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens Software Diploma\Anomalies Tracker\Anomalies-Tracker-Siemens-Academy\src\frontend\UiFiles\TaskTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task_Tab(object):
    def setupUi(self, Task_Tab):
        Task_Tab.setObjectName("Task_Tab")
        Task_Tab.resize(759, 456)
        Task_Tab.setStyleSheet("QWidget{\n"
"background-color:rgb(37, 40, 50);\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Task_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Task_tabWidget = QtWidgets.QTabWidget(Task_Tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Task_tabWidget.setFont(font)
        self.Task_tabWidget.setStyleSheet("\n"
"QTabWidget::pane{\n"
"border-color:none;\n"
"}\n"
"QTabWidget:tab-bar {\n"
"\n"
"border-color:none;\n"
"}\n"
"QTabBar:tab:selected{\n"
"background-color:#282c37;\n"
"color:white;\n"
"}\n"
"QTabBar:tab:!selected{\n"
"background-color:#1b1d22;\n"
"color:white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"")
        self.Task_tabWidget.setObjectName("Task_tabWidget")
        self.RunningConfig = QtWidgets.QWidget()
        self.RunningConfig.setObjectName("RunningConfig")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RunningConfig)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.AddRunConfig_horizontalLayout = QtWidgets.QHBoxLayout()
        self.AddRunConfig_horizontalLayout.setObjectName("AddRunConfig_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddRunConfig_horizontalLayout.addItem(spacerItem)
        self.RunningDelete_pushButton = QtWidgets.QPushButton(self.RunningConfig)
        self.RunningDelete_pushButton.setStyleSheet("background:none;\n"
"")
        self.RunningDelete_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.RunningDelete_pushButton.setIcon(icon)
        self.RunningDelete_pushButton.setIconSize(QtCore.QSize(29, 25))
        self.RunningDelete_pushButton.setObjectName("RunningDelete_pushButton")
        self.AddRunConfig_horizontalLayout.addWidget(self.RunningDelete_pushButton)
        self.AddRunningConfig_button = QtWidgets.QPushButton(self.RunningConfig)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddRunningConfig_button.sizePolicy().hasHeightForWidth())
        self.AddRunningConfig_button.setSizePolicy(sizePolicy)
        self.AddRunningConfig_button.setMinimumSize(QtCore.QSize(51, 41))
        self.AddRunningConfig_button.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AddRunningConfig_button.setFont(font)
        self.AddRunningConfig_button.setObjectName("AddRunningConfig_button")
        self.AddRunConfig_horizontalLayout.addWidget(self.AddRunningConfig_button)
        self.gridLayout_2.addLayout(self.AddRunConfig_horizontalLayout, 0, 0, 1, 1)
        self.RunningConfig_scrollArea = QtWidgets.QScrollArea(self.RunningConfig)
        self.RunningConfig_scrollArea.setWidgetResizable(True)
        self.RunningConfig_scrollArea.setObjectName("RunningConfig_scrollArea")
        self.RunningConfig_scroll = QtWidgets.QWidget()
        self.RunningConfig_scroll.setGeometry(QtCore.QRect(0, 0, 713, 336))
        self.RunningConfig_scroll.setObjectName("RunningConfig_scroll")
        self.RunningConfig_scrollArea.setWidget(self.RunningConfig_scroll)
        self.gridLayout_2.addWidget(self.RunningConfig_scrollArea, 1, 0, 1, 1)
        self.Task_tabWidget.addTab(self.RunningConfig, "")
        self.Environments = QtWidgets.QWidget()
        self.Environments.setStyleSheet("")
        self.Environments.setObjectName("Environments")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Environments)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Directory_widget = QtWidgets.QWidget(self.Environments)
        self.Directory_widget.setObjectName("Directory_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.Directory_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.Range_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Range_horizontalLayout.setObjectName("Range_horizontalLayout")
        self.Range_radioButton = QtWidgets.QRadioButton(self.Directory_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Range_radioButton.setFont(font)
        self.Range_radioButton.setObjectName("Range_radioButton")
        self.Range_horizontalLayout.addWidget(self.Range_radioButton)
        self.RangeFrom_label = QtWidgets.QLabel(self.Directory_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RangeFrom_label.setFont(font)
        self.RangeFrom_label.setLineWidth(0)
        self.RangeFrom_label.setObjectName("RangeFrom_label")
        self.Range_horizontalLayout.addWidget(self.RangeFrom_label)
        self.RangeFrom_lineEdit = QtWidgets.QLineEdit(self.Directory_widget)
        self.RangeFrom_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RangeFrom_lineEdit.setStyleSheet("")
        self.RangeFrom_lineEdit.setObjectName("RangeFrom_lineEdit")
        self.Range_horizontalLayout.addWidget(self.RangeFrom_lineEdit)
        self.RangeTo_label = QtWidgets.QLabel(self.Directory_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.RangeTo_label.setFont(font)
        self.RangeTo_label.setLineWidth(0)
        self.RangeTo_label.setObjectName("RangeTo_label")
        self.Range_horizontalLayout.addWidget(self.RangeTo_label)
        self.RangeTo_lineEdit = QtWidgets.QLineEdit(self.Directory_widget)
        self.RangeTo_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.RangeTo_lineEdit.setStyleSheet("")
        self.RangeTo_lineEdit.setObjectName("RangeTo_lineEdit")
        self.Range_horizontalLayout.addWidget(self.RangeTo_lineEdit)
        self.gridLayout.addLayout(self.Range_horizontalLayout, 2, 0, 1, 1)
        self.BinarySearch_horizontalLayout = QtWidgets.QHBoxLayout()
        self.BinarySearch_horizontalLayout.setObjectName("BinarySearch_horizontalLayout")
        self.BinarySearch_radioButton = QtWidgets.QRadioButton(self.Directory_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BinarySearch_radioButton.setFont(font)
        self.BinarySearch_radioButton.setObjectName("BinarySearch_radioButton")
        self.BinarySearch_horizontalLayout.addWidget(self.BinarySearch_radioButton)
        self.BinarySearchFrom_label = QtWidgets.QLabel(self.Directory_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BinarySearchFrom_label.setFont(font)
        self.BinarySearchFrom_label.setLineWidth(0)
        self.BinarySearchFrom_label.setObjectName("BinarySearchFrom_label")
        self.BinarySearch_horizontalLayout.addWidget(self.BinarySearchFrom_label)
        self.BinarySearchFrom_lineEdit = QtWidgets.QLineEdit(self.Directory_widget)
        self.BinarySearchFrom_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.BinarySearchFrom_lineEdit.setStyleSheet("")
        self.BinarySearchFrom_lineEdit.setObjectName("BinarySearchFrom_lineEdit")
        self.BinarySearch_horizontalLayout.addWidget(self.BinarySearchFrom_lineEdit)
        self.BinarySearchTo_label = QtWidgets.QLabel(self.Directory_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BinarySearchTo_label.setFont(font)
        self.BinarySearchTo_label.setLineWidth(0)
        self.BinarySearchTo_label.setObjectName("BinarySearchTo_label")
        self.BinarySearch_horizontalLayout.addWidget(self.BinarySearchTo_label)
        self.BinarySearchTo_lineEdit = QtWidgets.QLineEdit(self.Directory_widget)
        self.BinarySearchTo_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.BinarySearchTo_lineEdit.setStyleSheet("")
        self.BinarySearchTo_lineEdit.setObjectName("BinarySearchTo_lineEdit")
        self.BinarySearch_horizontalLayout.addWidget(self.BinarySearchTo_lineEdit)
        self.gridLayout.addLayout(self.BinarySearch_horizontalLayout, 3, 0, 1, 1)
        self.All_radioButton = QtWidgets.QRadioButton(self.Directory_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.All_radioButton.setFont(font)
        self.All_radioButton.setObjectName("All_radioButton")
        self.gridLayout.addWidget(self.All_radioButton, 1, 0, 1, 1)
        self.ParentDir_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ParentDir_horizontalLayout.setObjectName("ParentDir_horizontalLayout")
        self.ParentDir_label = QtWidgets.QLabel(self.Directory_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ParentDir_label.setFont(font)
        self.ParentDir_label.setLineWidth(0)
        self.ParentDir_label.setObjectName("ParentDir_label")
        self.ParentDir_horizontalLayout.addWidget(self.ParentDir_label)
        self.ParentDir_lineEdit = QtWidgets.QLineEdit(self.Directory_widget)
        self.ParentDir_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ParentDir_lineEdit.setStyleSheet("")
        self.ParentDir_lineEdit.setObjectName("ParentDir_lineEdit")
        self.ParentDir_horizontalLayout.addWidget(self.ParentDir_lineEdit)
        self.BrowseParentDir_button = QtWidgets.QToolButton(self.Directory_widget)
        self.BrowseParentDir_button.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BrowseParentDir_button.setIcon(icon1)
        self.BrowseParentDir_button.setObjectName("BrowseParentDir_button")
        self.ParentDir_horizontalLayout.addWidget(self.BrowseParentDir_button)
        self.gridLayout.addLayout(self.ParentDir_horizontalLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_4.addWidget(self.Directory_widget, 2, 0, 1, 1)
        self.File_widget = QtWidgets.QWidget(self.Environments)
        self.File_widget.setObjectName("File_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.File_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FilePath_horizontalLayout = QtWidgets.QHBoxLayout()
        self.FilePath_horizontalLayout.setObjectName("FilePath_horizontalLayout")
        self.FilePath_abel = QtWidgets.QLabel(self.File_widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.FilePath_abel.setFont(font)
        self.FilePath_abel.setLineWidth(0)
        self.FilePath_abel.setObjectName("FilePath_abel")
        self.FilePath_horizontalLayout.addWidget(self.FilePath_abel)
        self.FilePath_lineEdit = QtWidgets.QLineEdit(self.File_widget)
        self.FilePath_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.FilePath_lineEdit.setStyleSheet("")
        self.FilePath_lineEdit.setObjectName("FilePath_lineEdit")
        self.FilePath_horizontalLayout.addWidget(self.FilePath_lineEdit)
        self.BrowseFilePath_button = QtWidgets.QToolButton(self.File_widget)
        self.BrowseFilePath_button.setStyleSheet("")
        self.BrowseFilePath_button.setIcon(icon1)
        self.BrowseFilePath_button.setObjectName("BrowseFilePath_button")
        self.FilePath_horizontalLayout.addWidget(self.BrowseFilePath_button)
        self.gridLayout_3.addLayout(self.FilePath_horizontalLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.File_widget, 1, 0, 1, 1)
        self.Add_Dict_File_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Add_Dict_File_horizontalLayout.setObjectName("Add_Dict_File_horizontalLayout")
        self.AddDirectory_button = QtWidgets.QPushButton(self.Environments)
        self.AddDirectory_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AddDirectory_button.setFont(font)
        self.AddDirectory_button.setObjectName("AddDirectory_button")
        self.Add_Dict_File_horizontalLayout.addWidget(self.AddDirectory_button)
        self.AddFile_button = QtWidgets.QPushButton(self.Environments)
        self.AddFile_button.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AddFile_button.setFont(font)
        self.AddFile_button.setObjectName("AddFile_button")
        self.Add_Dict_File_horizontalLayout.addWidget(self.AddFile_button)
        self.gridLayout_4.addLayout(self.Add_Dict_File_horizontalLayout, 0, 0, 1, 1)
        self.Task_tabWidget.addTab(self.Environments, "")
        self.Design = QtWidgets.QWidget()
        self.Design.setStyleSheet("")
        self.Design.setObjectName("Design")
        self.formLayout = QtWidgets.QFormLayout(self.Design)
        self.formLayout.setObjectName("formLayout")
        self.AddDesign_horizontalLayout = QtWidgets.QHBoxLayout()
        self.AddDesign_horizontalLayout.setObjectName("AddDesign_horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddDesign_horizontalLayout.addItem(spacerItem3)
        self.DesignDelete_pushButton = QtWidgets.QPushButton(self.Design)
        self.DesignDelete_pushButton.setStyleSheet("background:none;")
        self.DesignDelete_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\Siemens Software Diploma\\Anomalies Tracker\\Anomalies-Tracker-Siemens-Academy\\src\\frontend\\UiFiles\\../IconsImages/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DesignDelete_pushButton.setIcon(icon2)
        self.DesignDelete_pushButton.setIconSize(QtCore.QSize(30, 25))
        self.DesignDelete_pushButton.setObjectName("DesignDelete_pushButton")
        self.AddDesign_horizontalLayout.addWidget(self.DesignDelete_pushButton)
        self.AddDesign_button = QtWidgets.QPushButton(self.Design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddDesign_button.sizePolicy().hasHeightForWidth())
        self.AddDesign_button.setSizePolicy(sizePolicy)
        self.AddDesign_button.setMinimumSize(QtCore.QSize(51, 41))
        self.AddDesign_button.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AddDesign_button.setFont(font)
        self.AddDesign_button.setIconSize(QtCore.QSize(16, 16))
        self.AddDesign_button.setObjectName("AddDesign_button")
        self.AddDesign_horizontalLayout.addWidget(self.AddDesign_button)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.AddDesign_horizontalLayout)
        self.Designs_scrollArea = QtWidgets.QScrollArea(self.Design)
        self.Designs_scrollArea.setWidgetResizable(True)
        self.Designs_scrollArea.setObjectName("Designs_scrollArea")
        self.Designs_scrollAreaWidget = QtWidgets.QWidget()
        self.Designs_scrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 713, 85))
        self.Designs_scrollAreaWidget.setObjectName("Designs_scrollAreaWidget")
        self.Designs_scrollArea.setWidget(self.Designs_scrollAreaWidget)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.Designs_scrollArea)
        self.Task_tabWidget.addTab(self.Design, "")
        self.verticalLayout.addWidget(self.Task_tabWidget)

        self.retranslateUi(Task_Tab)
        self.Task_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Task_Tab)

    def retranslateUi(self, Task_Tab):
        _translate = QtCore.QCoreApplication.translate
        Task_Tab.setWindowTitle(_translate("Task_Tab", "Form"))
        self.AddRunningConfig_button.setText(_translate("Task_Tab", "+"))
        self.Task_tabWidget.setTabText(self.Task_tabWidget.indexOf(self.RunningConfig), _translate("Task_Tab", "Running Configurations"))
        self.Range_radioButton.setText(_translate("Task_Tab", "Range"))
        self.RangeFrom_label.setText(_translate("Task_Tab", "From"))
        self.RangeTo_label.setText(_translate("Task_Tab", "To"))
        self.BinarySearch_radioButton.setText(_translate("Task_Tab", "Binary Search"))
        self.BinarySearchFrom_label.setText(_translate("Task_Tab", "From"))
        self.BinarySearchTo_label.setText(_translate("Task_Tab", "To"))
        self.All_radioButton.setText(_translate("Task_Tab", "All"))
        self.ParentDir_label.setText(_translate("Task_Tab", "Parent Directory"))
        self.BrowseParentDir_button.setText(_translate("Task_Tab", "..."))
        self.FilePath_abel.setText(_translate("Task_Tab", "File Path"))
        self.BrowseFilePath_button.setText(_translate("Task_Tab", "..."))
        self.AddDirectory_button.setText(_translate("Task_Tab", "Add Directory"))
        self.AddFile_button.setText(_translate("Task_Tab", "Add File"))
        self.Task_tabWidget.setTabText(self.Task_tabWidget.indexOf(self.Environments), _translate("Task_Tab", "Environments"))
        self.AddDesign_button.setText(_translate("Task_Tab", "+"))
        self.Task_tabWidget.setTabText(self.Task_tabWidget.indexOf(self.Design), _translate("Task_Tab", "Design"))
