# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(727, 210)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        GroupBox.setFont(font)
        GroupBox.setStyleSheet("QGroupBox{\n"
"background-color:rgb(37, 40, 50);\n"
"color: white;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"\n"
"}\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.databaseLabel_2 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.databaseLabel_2.setFont(font)
        self.databaseLabel_2.setLineWidth(0)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.horizontalLayout_4.addWidget(self.databaseLabel_2)
        self.lineEditDatabasePath_2 = QtWidgets.QLineEdit(GroupBox)
        self.lineEditDatabasePath_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_2.setStyleSheet("")
        self.lineEditDatabasePath_2.setObjectName("lineEditDatabasePath_2")
        self.horizontalLayout_4.addWidget(self.lineEditDatabasePath_2)
        self.toolButtonBrowseDatabase_3 = QtWidgets.QToolButton(GroupBox)
        self.toolButtonBrowseDatabase_3.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBrowseDatabase_3.setIcon(icon)
        self.toolButtonBrowseDatabase_3.setObjectName("toolButtonBrowseDatabase_3")
        self.horizontalLayout_4.addWidget(self.toolButtonBrowseDatabase_3)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonAdd_3 = QtWidgets.QPushButton(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd_3.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd_3.setSizePolicy(sizePolicy)
        self.pushButtonAdd_3.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAdd_3.setFont(font)
        self.pushButtonAdd_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonAdd_3.setStyleSheet("")
        self.pushButtonAdd_3.setObjectName("pushButtonAdd_3")
        self.horizontalLayout_5.addWidget(self.pushButtonAdd_3)
        self.pushButtonAdd_4 = QtWidgets.QPushButton(GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd_4.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd_4.setSizePolicy(sizePolicy)
        self.pushButtonAdd_4.setMinimumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAdd_4.setFont(font)
        self.pushButtonAdd_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonAdd_4.setStyleSheet("")
        self.pushButtonAdd_4.setObjectName("pushButtonAdd_4")
        self.horizontalLayout_5.addWidget(self.pushButtonAdd_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        GroupBox.setTitle(_translate("GroupBox", "Design"))
        self.databaseLabel_2.setText(_translate("GroupBox", "Design Path"))
        self.toolButtonBrowseDatabase_3.setText(_translate("GroupBox", "..."))
        self.pushButtonAdd_3.setText(_translate("GroupBox", "Compilation configuration"))
        self.pushButtonAdd_4.setText(_translate("GroupBox", "Launching Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupBox = QtWidgets.QGroupBox()
    ui = Ui_GroupBox()
    ui.setupUi(GroupBox)
    GroupBox.show()
    sys.exit(app.exec_())
