# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DUT_Config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DutConf_Form(object):
    def setupUi(self, DutConf_Form):
        DutConf_Form.setObjectName("DutConf_Form")
        DutConf_Form.resize(767, 607)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(DutConf_Form.sizePolicy().hasHeightForWidth())
        DutConf_Form.setSizePolicy(sizePolicy)
        DutConf_Form.setStyleSheet("/* QFrame */\n"
"QWidget {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(37, 40, 50);\n"
"}\n"
"/* Label */\n"
"QLabel{\n"
"background-color:none;\n"
"    color: rgb(255, 255, 255);\n"
"font-size:22px;\n"
"font:normal;\n"
"\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"/* Button */\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    background-color:#1b1d23;\n"
"    color: rgb(255, 255, 255);\n"
"    margin:10px;\n"
"    padding:5px;\n"
"font:bold 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"/* ComboBox */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QFrame QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QComboBox {\n"
"    background-color: rgb(52, 59, 72);\n"
"    border: 1px solid rgb(49, 54, 65);\n"
"    height: 30px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    padding-right: 15px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size:22px;\n"
"    font:normal; \n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color:rgb(27, 29, 35);\n"
"    border: 0px;\n"
"    color: #fff;\n"
"    selection-background-color: rgb(22, 51, 79);\n"
"    outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgb(22, 51, 79);\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(\":/icons/icons/cil-chevron-bottom.png\");\n"
"    width:15px;\n"
"    height:15px;\n"
"    margin-right:15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 0px solid rgb(61, 70, 86);\n"
"    background-color: rgb(57, 65, 80)\n"
"}\n"
"QComboBox QListView {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 10px;\n"
"    color: #FFF;\n"
"    padding: 10px;\n"
"}\n"
"QComboBox:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* QGroupBox  */\n"
"QGroupBox::title{\n"
"    color: rgb(255, 255, 255);\n"
"    margin-top: 10px;\n"
"    bottom: 20px;\n"
"}\n"
"QGroupBox{\n"
"    margin-top: 40px;\n"
"    margin-left: 20px;\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    padding-top: 20px;\n"
"}\n"
"/* LineEdit */\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"    font-size:20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* Table */\n"
"QFrame QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QFrame QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar::handle:vertical {\n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    color: white;\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"/* Splitter */\n"
"QSplitter::handle{\n"
"    background-color: gray;\n"
"border-radius:7px;\n"
"font:normal;\n"
"font-size:22px;\n"
"padding-left:8px\n"
"}\n"
"QGroupBox\n"
"{\n"
"font:22px;\n"
"font:bold;\n"
"border-color:white;\n"
"}\n"
"QCheckBox\n"
"{\n"
"background-color:none;\n"
"    font-size:22px;\n"
"    font:normal; \n"
"     color:white;\n"
"}\n"
"QSpinBox\n"
"{\n"
"\n"
"background-color:#1b1d23;\n"
"border-radius:7px;\n"
"font:normal;\n"
"font-size:22px;\n"
"padding-left:8px;\n"
"color:white;\n"
"}\n"
"QListWidget\n"
"{\n"
"    font-size:18px;\n"
"    font:normal; \n"
"     color:white;\n"
"    background-color: rgb(52, 59, 72);\n"
"\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DutConf_Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(DutConf_Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 731, 1615))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DutConfig_groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.DutConfig_groupBox.sizePolicy().hasHeightForWidth())
        self.DutConfig_groupBox.setSizePolicy(sizePolicy)
        self.DutConfig_groupBox.setStyleSheet("    margin-left: 0px;\n"
"")
        self.DutConfig_groupBox.setObjectName("DutConfig_groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.DutConfig_groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.TerminateDPIOnError_checkBox = QtWidgets.QCheckBox(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.TerminateDPIOnError_checkBox.sizePolicy().hasHeightForWidth())
        self.TerminateDPIOnError_checkBox.setSizePolicy(sizePolicy)
        self.TerminateDPIOnError_checkBox.setStyleSheet("background-color:none;")
        self.TerminateDPIOnError_checkBox.setObjectName("TerminateDPIOnError_checkBox")
        self.gridLayout.addWidget(self.TerminateDPIOnError_checkBox, 0, 0, 1, 1)
        self.TermianteDPI_checkBox = QtWidgets.QCheckBox(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TermianteDPI_checkBox.sizePolicy().hasHeightForWidth())
        self.TermianteDPI_checkBox.setSizePolicy(sizePolicy)
        self.TermianteDPI_checkBox.setMinimumSize(QtCore.QSize(0, 0))
        self.TermianteDPI_checkBox.setStyleSheet("")
        self.TermianteDPI_checkBox.setObjectName("TermianteDPI_checkBox")
        self.gridLayout.addWidget(self.TermianteDPI_checkBox, 1, 0, 1, 1)
        self.LanuchDPI_checkBox = QtWidgets.QCheckBox(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LanuchDPI_checkBox.sizePolicy().hasHeightForWidth())
        self.LanuchDPI_checkBox.setSizePolicy(sizePolicy)
        self.LanuchDPI_checkBox.setStyleSheet("font-size:22px;\n"
"font:normal;\n"
"background:none;")
        self.LanuchDPI_checkBox.setObjectName("LanuchDPI_checkBox")
        self.gridLayout.addWidget(self.LanuchDPI_checkBox, 2, 0, 1, 1)
        self.AVBList_Vlayout = QtWidgets.QHBoxLayout()
        self.AVBList_Vlayout.setObjectName("AVBList_Vlayout")
        self.AVBList_label = QtWidgets.QLabel(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AVBList_label.sizePolicy().hasHeightForWidth())
        self.AVBList_label.setSizePolicy(sizePolicy)
        self.AVBList_label.setMinimumSize(QtCore.QSize(0, 0))
        self.AVBList_label.setStyleSheet("")
        self.AVBList_label.setObjectName("AVBList_label")
        self.AVBList_Vlayout.addWidget(self.AVBList_label)
        self.AVB_ListView = QtWidgets.QListWidget(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.AVB_ListView.sizePolicy().hasHeightForWidth())
        self.AVB_ListView.setSizePolicy(sizePolicy)
        self.AVB_ListView.setMinimumSize(QtCore.QSize(0, 0))
        self.AVB_ListView.setMaximumSize(QtCore.QSize(200000, 75))
        self.AVB_ListView.setSizeIncrement(QtCore.QSize(0, 0))
        self.AVB_ListView.setBaseSize(QtCore.QSize(0, 0))
        self.AVB_ListView.setAutoFillBackground(False)
        self.AVB_ListView.setStyleSheet("QListWidget:Item\n"
"{\n"
"font-size:10px;\n"
"}\n"
"\n"
"QListWidget:Icon\n"
"{\n"
"size:15px;\n"
"\n"
"}\n"
"\n"
"QListWidget\n"
"{\n"
"padding:5px;\n"
"}")
        self.AVB_ListView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AVB_ListView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.AVB_ListView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.AVB_ListView.setAutoScroll(False)
        self.AVB_ListView.setAutoScrollMargin(0)
        self.AVB_ListView.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.AVB_ListView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.AVB_ListView.setAlternatingRowColors(False)
        self.AVB_ListView.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.AVB_ListView.setIconSize(QtCore.QSize(0, 0))
        self.AVB_ListView.setTextElideMode(QtCore.Qt.ElideNone)
        self.AVB_ListView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.AVB_ListView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.AVB_ListView.setMovement(QtWidgets.QListView.Static)
        self.AVB_ListView.setFlow(QtWidgets.QListView.LeftToRight)
        self.AVB_ListView.setProperty("isWrapping", True)
        self.AVB_ListView.setResizeMode(QtWidgets.QListView.Adjust)
        self.AVB_ListView.setLayoutMode(QtWidgets.QListView.Batched)
        self.AVB_ListView.setGridSize(QtCore.QSize(52, 32))
        self.AVB_ListView.setViewMode(QtWidgets.QListView.ListMode)
        self.AVB_ListView.setModelColumn(0)
        self.AVB_ListView.setUniformItemSizes(True)
        self.AVB_ListView.setBatchSize(7)
        self.AVB_ListView.setWordWrap(True)
        self.AVB_ListView.setSelectionRectVisible(False)
        self.AVB_ListView.setObjectName("AVB_ListView")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.AVB_ListView.addItem(item)
        self.AVBList_Vlayout.addWidget(self.AVB_ListView)
        self.gridLayout.addLayout(self.AVBList_Vlayout, 3, 0, 1, 1)
        self.DesignPath_Hlayout = QtWidgets.QHBoxLayout()
        self.DesignPath_Hlayout.setObjectName("DesignPath_Hlayout")
        self.DesignPath_label = QtWidgets.QLabel(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesignPath_label.sizePolicy().hasHeightForWidth())
        self.DesignPath_label.setSizePolicy(sizePolicy)
        self.DesignPath_label.setStyleSheet("font-size:22px;\n"
"font:normal;\n"
"")
        self.DesignPath_label.setObjectName("DesignPath_label")
        self.DesignPath_Hlayout.addWidget(self.DesignPath_label)
        self.DesignPath_lineEdit = QtWidgets.QLineEdit(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DesignPath_lineEdit.sizePolicy().hasHeightForWidth())
        self.DesignPath_lineEdit.setSizePolicy(sizePolicy)
        self.DesignPath_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.DesignPath_lineEdit.setObjectName("DesignPath_lineEdit")
        self.DesignPath_Hlayout.addWidget(self.DesignPath_lineEdit)
        self.DesignPath_toolButton = QtWidgets.QToolButton(self.DutConfig_groupBox)
        self.DesignPath_toolButton.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.DesignPath_toolButton.setObjectName("DesignPath_toolButton")
        self.DesignPath_Hlayout.addWidget(self.DesignPath_toolButton)
        self.gridLayout.addLayout(self.DesignPath_Hlayout, 4, 0, 1, 1)
        self.RecordConf_Groupbox = QtWidgets.QGroupBox(self.DutConfig_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(28)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordConf_Groupbox.sizePolicy().hasHeightForWidth())
        self.RecordConf_Groupbox.setSizePolicy(sizePolicy)
        self.RecordConf_Groupbox.setStyleSheet("    border:none;\n"
"")
        self.RecordConf_Groupbox.setObjectName("RecordConf_Groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.RecordConf_Groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RecordDir_label = QtWidgets.QLabel(self.RecordConf_Groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordDir_label.sizePolicy().hasHeightForWidth())
        self.RecordDir_label.setSizePolicy(sizePolicy)
        self.RecordDir_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.RecordDir_label.setObjectName("RecordDir_label")
        self.horizontalLayout_3.addWidget(self.RecordDir_label)
        self.RecordDir_lineEdit = QtWidgets.QLineEdit(self.RecordConf_Groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RecordDir_lineEdit.sizePolicy().hasHeightForWidth())
        self.RecordDir_lineEdit.setSizePolicy(sizePolicy)
        self.RecordDir_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.RecordDir_lineEdit.setObjectName("RecordDir_lineEdit")
        self.horizontalLayout_3.addWidget(self.RecordDir_lineEdit)
        self.RecordDir_toolButton = QtWidgets.QToolButton(self.RecordConf_Groupbox)
        self.RecordDir_toolButton.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.RecordDir_toolButton.setObjectName("RecordDir_toolButton")
        self.horizontalLayout_3.addWidget(self.RecordDir_toolButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.Snapshots_GroupBox = QtWidgets.QGroupBox(self.RecordConf_Groupbox)
        self.Snapshots_GroupBox.setObjectName("Snapshots_GroupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Snapshots_GroupBox)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ConfigType_Hlayout = QtWidgets.QHBoxLayout()
        self.ConfigType_Hlayout.setContentsMargins(-1, 5, -1, 5)
        self.ConfigType_Hlayout.setObjectName("ConfigType_Hlayout")
        self.ConfigType_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfigType_label.sizePolicy().hasHeightForWidth())
        self.ConfigType_label.setSizePolicy(sizePolicy)
        self.ConfigType_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ConfigType_label.setObjectName("ConfigType_label")
        self.ConfigType_Hlayout.addWidget(self.ConfigType_label)
        self.ConfigType_comboBox = QtWidgets.QComboBox(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(56)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.ConfigType_comboBox.sizePolicy().hasHeightForWidth())
        self.ConfigType_comboBox.setSizePolicy(sizePolicy)
        self.ConfigType_comboBox.setAutoFillBackground(False)
        self.ConfigType_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.ConfigType_comboBox.setObjectName("ConfigType_comboBox")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_comboBox.addItem("")
        self.ConfigType_Hlayout.addWidget(self.ConfigType_comboBox)
        self.verticalLayout_11.addLayout(self.ConfigType_Hlayout)
        self.ConfigValue_Vlayout = QtWidgets.QVBoxLayout()
        self.ConfigValue_Vlayout.setObjectName("ConfigValue_Vlayout")
        self.FromConfigValue_Hlayout = QtWidgets.QHBoxLayout()
        self.FromConfigValue_Hlayout.setObjectName("FromConfigValue_Hlayout")
        self.FromConfigValue_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FromConfigValue_label.sizePolicy().hasHeightForWidth())
        self.FromConfigValue_label.setSizePolicy(sizePolicy)
        self.FromConfigValue_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.FromConfigValue_label.setObjectName("FromConfigValue_label")
        self.FromConfigValue_Hlayout.addWidget(self.FromConfigValue_label)
        self.FromConfigValue_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FromConfigValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.FromConfigValue_lineEdit.setSizePolicy(sizePolicy)
        self.FromConfigValue_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"font:normal;\n"
"")
        self.FromConfigValue_lineEdit.setObjectName("FromConfigValue_lineEdit")
        self.FromConfigValue_Hlayout.addWidget(self.FromConfigValue_lineEdit)
        self.ConfigValue_Vlayout.addLayout(self.FromConfigValue_Hlayout)
        self.ToConfigValue_Hlayout = QtWidgets.QHBoxLayout()
        self.ToConfigValue_Hlayout.setObjectName("ToConfigValue_Hlayout")
        self.ToConfigValue_label = QtWidgets.QLabel(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.ToConfigValue_label.sizePolicy().hasHeightForWidth())
        self.ToConfigValue_label.setSizePolicy(sizePolicy)
        self.ToConfigValue_label.setMinimumSize(QtCore.QSize(0, 0))
        self.ToConfigValue_label.setObjectName("ToConfigValue_label")
        self.ToConfigValue_Hlayout.addWidget(self.ToConfigValue_label)
        self.ToConfigValue_lineEdit = QtWidgets.QLineEdit(self.Snapshots_GroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToConfigValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.ToConfigValue_lineEdit.setSizePolicy(sizePolicy)
        self.ToConfigValue_lineEdit.setObjectName("ToConfigValue_lineEdit")
        self.ToConfigValue_Hlayout.addWidget(self.ToConfigValue_lineEdit)
        self.ConfigValue_Vlayout.addLayout(self.ToConfigValue_Hlayout)
        self.verticalLayout_11.addLayout(self.ConfigValue_Vlayout)
        self.gridLayout_2.addWidget(self.Snapshots_GroupBox, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.RecordConf_Groupbox, 5, 0, 1, 1)
        self.ReplyConf_groupbox = QtWidgets.QGroupBox(self.DutConfig_groupBox)
        self.ReplyConf_groupbox.setStyleSheet("    border:none;\n"
"")
        self.ReplyConf_groupbox.setObjectName("ReplyConf_groupbox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ReplyConf_groupbox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ReplyDir_Hlayout = QtWidgets.QHBoxLayout()
        self.ReplyDir_Hlayout.setObjectName("ReplyDir_Hlayout")
        self.ReplyDir_label = QtWidgets.QLabel(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplyDir_label.sizePolicy().hasHeightForWidth())
        self.ReplyDir_label.setSizePolicy(sizePolicy)
        self.ReplyDir_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ReplyDir_label.setObjectName("ReplyDir_label")
        self.ReplyDir_Hlayout.addWidget(self.ReplyDir_label)
        self.ReplyDir_lineEdit = QtWidgets.QLineEdit(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplyDir_lineEdit.sizePolicy().hasHeightForWidth())
        self.ReplyDir_lineEdit.setSizePolicy(sizePolicy)
        self.ReplyDir_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ReplyDir_lineEdit.setObjectName("ReplyDir_lineEdit")
        self.ReplyDir_Hlayout.addWidget(self.ReplyDir_lineEdit)
        self.ReplyDir_toolButton = QtWidgets.QToolButton(self.ReplyConf_groupbox)
        self.ReplyDir_toolButton.setStyleSheet("QToolButton{\n"
"background-color:none;\n"
"border:none;\n"
"}\n"
"QToolButton:hover{\n"
"background-color: #394150;\n"
"border-radius:13px;\n"
"}")
        self.ReplyDir_toolButton.setObjectName("ReplyDir_toolButton")
        self.ReplyDir_Hlayout.addWidget(self.ReplyDir_toolButton)
        self.verticalLayout_7.addLayout(self.ReplyDir_Hlayout)
        self.ReplySnapshotName_Hlayout = QtWidgets.QHBoxLayout()
        self.ReplySnapshotName_Hlayout.setObjectName("ReplySnapshotName_Hlayout")
        self.ReplySnapshotName_label = QtWidgets.QLabel(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplySnapshotName_label.sizePolicy().hasHeightForWidth())
        self.ReplySnapshotName_label.setSizePolicy(sizePolicy)
        self.ReplySnapshotName_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.ReplySnapshotName_label.setObjectName("ReplySnapshotName_label")
        self.ReplySnapshotName_Hlayout.addWidget(self.ReplySnapshotName_label)
        self.ReplySnapshotName_lineEdit = QtWidgets.QLineEdit(self.ReplyConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ReplySnapshotName_lineEdit.sizePolicy().hasHeightForWidth())
        self.ReplySnapshotName_lineEdit.setSizePolicy(sizePolicy)
        self.ReplySnapshotName_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ReplySnapshotName_lineEdit.setObjectName("ReplySnapshotName_lineEdit")
        self.ReplySnapshotName_Hlayout.addWidget(self.ReplySnapshotName_lineEdit)
        self.verticalLayout_7.addLayout(self.ReplySnapshotName_Hlayout)
        self.gridLayout.addWidget(self.ReplyConf_groupbox, 6, 0, 1, 1)
        self.DPIConf_groupbox = QtWidgets.QGroupBox(self.DutConfig_groupBox)
        self.DPIConf_groupbox.setStyleSheet("    border:none;\n"
"")
        self.DPIConf_groupbox.setObjectName("DPIConf_groupbox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.DPIConf_groupbox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.DPILaunchModeHLayout = QtWidgets.QHBoxLayout()
        self.DPILaunchModeHLayout.setObjectName("DPILaunchModeHLayout")
        self.DPILaunchMode_label = QtWidgets.QLabel(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchMode_label.sizePolicy().hasHeightForWidth())
        self.DPILaunchMode_label.setSizePolicy(sizePolicy)
        self.DPILaunchMode_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DPILaunchMode_label.setObjectName("DPILaunchMode_label")
        self.DPILaunchModeHLayout.addWidget(self.DPILaunchMode_label)
        self.DPILaunchMode_lineEdit = QtWidgets.QLineEdit(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchMode_lineEdit.sizePolicy().hasHeightForWidth())
        self.DPILaunchMode_lineEdit.setSizePolicy(sizePolicy)
        self.DPILaunchMode_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.DPILaunchMode_lineEdit.setObjectName("DPILaunchMode_lineEdit")
        self.DPILaunchModeHLayout.addWidget(self.DPILaunchMode_lineEdit)
        self.verticalLayout_8.addLayout(self.DPILaunchModeHLayout)
        self.DPILaunchType_HLayout = QtWidgets.QHBoxLayout()
        self.DPILaunchType_HLayout.setContentsMargins(-1, 5, -1, 5)
        self.DPILaunchType_HLayout.setObjectName("DPILaunchType_HLayout")
        self.DPILaunchType_label = QtWidgets.QLabel(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.DPILaunchType_label.sizePolicy().hasHeightForWidth())
        self.DPILaunchType_label.setSizePolicy(sizePolicy)
        self.DPILaunchType_label.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.DPILaunchType_label.setObjectName("DPILaunchType_label")
        self.DPILaunchType_HLayout.addWidget(self.DPILaunchType_label)
        self.DPILaunchType_comboBox = QtWidgets.QComboBox(self.DPIConf_groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DPILaunchType_comboBox.sizePolicy().hasHeightForWidth())
        self.DPILaunchType_comboBox.setSizePolicy(sizePolicy)
        self.DPILaunchType_comboBox.setStyleSheet("background-color:#343b48;\n"
"font:normal;\n"
"font-size:22px;\n"
"border-radius:7px;")
        self.DPILaunchType_comboBox.setObjectName("DPILaunchType_comboBox")
        self.DPILaunchType_comboBox.addItem("")
        self.DPILaunchType_comboBox.addItem("")
        self.DPILaunchType_comboBox.addItem("")
        self.DPILaunchType_comboBox.addItem("")
        self.DPILaunchType_HLayout.addWidget(self.DPILaunchType_comboBox)
        self.verticalLayout_8.addLayout(self.DPILaunchType_HLayout)
        self.DPIAdditionalArgGroupBox = QtWidgets.QGroupBox(self.DPIConf_groupbox)
        self.DPIAdditionalArgGroupBox.setObjectName("DPIAdditionalArgGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DPIAdditionalArgGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ArgName_Hlayout = QtWidgets.QHBoxLayout()
        self.ArgName_Hlayout.setObjectName("ArgName_Hlayout")
        self.ArgName_label = QtWidgets.QLabel(self.DPIAdditionalArgGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgName_label.sizePolicy().hasHeightForWidth())
        self.ArgName_label.setSizePolicy(sizePolicy)
        self.ArgName_label.setObjectName("ArgName_label")
        self.ArgName_Hlayout.addWidget(self.ArgName_label)
        self.ArgName_HSpacer_mid_lineEdit = QtWidgets.QLineEdit(self.DPIAdditionalArgGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgName_HSpacer_mid_lineEdit.sizePolicy().hasHeightForWidth())
        self.ArgName_HSpacer_mid_lineEdit.setSizePolicy(sizePolicy)
        self.ArgName_HSpacer_mid_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ArgName_HSpacer_mid_lineEdit.setObjectName("ArgName_HSpacer_mid_lineEdit")
        self.ArgName_Hlayout.addWidget(self.ArgName_HSpacer_mid_lineEdit)
        self.gridLayout_3.addLayout(self.ArgName_Hlayout, 0, 0, 1, 1)
        self.ArgValue_Hlayout = QtWidgets.QHBoxLayout()
        self.ArgValue_Hlayout.setObjectName("ArgValue_Hlayout")
        self.ArgValue_label = QtWidgets.QLabel(self.DPIAdditionalArgGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgValue_label.sizePolicy().hasHeightForWidth())
        self.ArgValue_label.setSizePolicy(sizePolicy)
        self.ArgValue_label.setObjectName("ArgValue_label")
        self.ArgValue_Hlayout.addWidget(self.ArgValue_label)
        self.ArgValue_lineEdit = QtWidgets.QLineEdit(self.DPIAdditionalArgGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ArgValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.ArgValue_lineEdit.setSizePolicy(sizePolicy)
        self.ArgValue_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.ArgValue_lineEdit.setObjectName("ArgValue_lineEdit")
        self.ArgValue_Hlayout.addWidget(self.ArgValue_lineEdit)
        self.gridLayout_3.addLayout(self.ArgValue_Hlayout, 1, 0, 1, 1)
        self.DPIAdditionalArg = QtWidgets.QTextBrowser(self.DPIAdditionalArgGroupBox)
        self.DPIAdditionalArg.setObjectName("DPIAdditionalArg")
        self.gridLayout_3.addWidget(self.DPIAdditionalArg, 2, 0, 1, 1)
        self.AddArgLayout_4 = QtWidgets.QHBoxLayout()
        self.AddArgLayout_4.setObjectName("AddArgLayout_4")
        spacerItem = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddArgLayout_4.addItem(spacerItem)
        self.AddArgButton = QtWidgets.QPushButton(self.DPIAdditionalArgGroupBox)
        self.AddArgButton.setMinimumSize(QtCore.QSize(111, 54))
        self.AddArgButton.setObjectName("AddArgButton")
        self.AddArgLayout_4.addWidget(self.AddArgButton)
        self.gridLayout_3.addLayout(self.AddArgLayout_4, 3, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.DPIAdditionalArgGroupBox)
        self.DPIAdditionalArg_groupBox = QtWidgets.QGroupBox(self.DPIConf_groupbox)
        self.DPIAdditionalArg_groupBox.setObjectName("DPIAdditionalArg_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.DPIAdditionalArg_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DPIAdditionalEnvValues = QtWidgets.QTextBrowser(self.DPIAdditionalArg_groupBox)
        self.DPIAdditionalEnvValues.setObjectName("DPIAdditionalEnvValues")
        self.gridLayout_4.addWidget(self.DPIAdditionalEnvValues, 5, 0, 1, 1)
        self.EnvVarName_Hlayout = QtWidgets.QHBoxLayout()
        self.EnvVarName_Hlayout.setObjectName("EnvVarName_Hlayout")
        self.EnvVarName_label = QtWidgets.QLabel(self.DPIAdditionalArg_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarName_label.sizePolicy().hasHeightForWidth())
        self.EnvVarName_label.setSizePolicy(sizePolicy)
        self.EnvVarName_label.setObjectName("EnvVarName_label")
        self.EnvVarName_Hlayout.addWidget(self.EnvVarName_label)
        self.EnvVarName_HSpacer_mid_lineEdit = QtWidgets.QLineEdit(self.DPIAdditionalArg_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarName_HSpacer_mid_lineEdit.sizePolicy().hasHeightForWidth())
        self.EnvVarName_HSpacer_mid_lineEdit.setSizePolicy(sizePolicy)
        self.EnvVarName_HSpacer_mid_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.EnvVarName_HSpacer_mid_lineEdit.setObjectName("EnvVarName_HSpacer_mid_lineEdit")
        self.EnvVarName_Hlayout.addWidget(self.EnvVarName_HSpacer_mid_lineEdit)
        self.gridLayout_4.addLayout(self.EnvVarName_Hlayout, 1, 0, 1, 2)
        self.EnvVarValue_Hlayout = QtWidgets.QHBoxLayout()
        self.EnvVarValue_Hlayout.setObjectName("EnvVarValue_Hlayout")
        self.EnvVarValue_label = QtWidgets.QLabel(self.DPIAdditionalArg_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarValue_label.sizePolicy().hasHeightForWidth())
        self.EnvVarValue_label.setSizePolicy(sizePolicy)
        self.EnvVarValue_label.setObjectName("EnvVarValue_label")
        self.EnvVarValue_Hlayout.addWidget(self.EnvVarValue_label)
        self.EnvVarValue_lineEdit = QtWidgets.QLineEdit(self.DPIAdditionalArg_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvVarValue_lineEdit.sizePolicy().hasHeightForWidth())
        self.EnvVarValue_lineEdit.setSizePolicy(sizePolicy)
        self.EnvVarValue_lineEdit.setStyleSheet("background-color: #1b1d23;\n"
"")
        self.EnvVarValue_lineEdit.setObjectName("EnvVarValue_lineEdit")
        self.EnvVarValue_Hlayout.addWidget(self.EnvVarValue_lineEdit)
        self.gridLayout_4.addLayout(self.EnvVarValue_Hlayout, 3, 0, 1, 2)
        self.AddEnvLayout_5 = QtWidgets.QHBoxLayout()
        self.AddEnvLayout_5.setObjectName("AddEnvLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(528, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.AddEnvLayout_5.addItem(spacerItem1)
        self.AddEnv = QtWidgets.QPushButton(self.DPIAdditionalArg_groupBox)
        self.AddEnv.setMinimumSize(QtCore.QSize(111, 54))
        self.AddEnv.setObjectName("AddEnv")
        self.AddEnvLayout_5.addWidget(self.AddEnv)
        self.gridLayout_4.addLayout(self.AddEnvLayout_5, 6, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.DPIAdditionalArg_groupBox)
        self.gridLayout.addWidget(self.DPIConf_groupbox, 7, 0, 1, 1)
        self.CustomComConf_Vlayout = QtWidgets.QVBoxLayout()
        self.CustomComConf_Vlayout.setObjectName("CustomComConf_Vlayout")
        self.CustomComConf_checkbox = QtWidgets.QCheckBox(self.DutConfig_groupBox)
        self.CustomComConf_checkbox.setStyleSheet("font-size:22px;\n"
"font:normal")
        self.CustomComConf_checkbox.setObjectName("CustomComConf_checkbox")
        self.CustomComConf_Vlayout.addWidget(self.CustomComConf_checkbox)
        self.gridLayout.addLayout(self.CustomComConf_Vlayout, 8, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.DutConfig_groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(DutConf_Form)
        self.AVB_ListView.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(DutConf_Form)

    def retranslateUi(self, DutConf_Form):
        _translate = QtCore.QCoreApplication.translate
        DutConf_Form.setWindowTitle(_translate("DutConf_Form", "Form"))
        self.DutConfig_groupBox.setTitle(_translate("DutConf_Form", "Dut Configuration"))
        self.TerminateDPIOnError_checkBox.setText(_translate("DutConf_Form", "  Lanuch DPI"))
        self.TermianteDPI_checkBox.setText(_translate("DutConf_Form", "  Terminate DPI"))
        self.LanuchDPI_checkBox.setText(_translate("DutConf_Form", "  Terminate DPI on Error"))
        self.AVBList_label.setText(_translate("DutConf_Form", "AVB List"))
        __sortingEnabled = self.AVB_ListView.isSortingEnabled()
        self.AVB_ListView.setSortingEnabled(False)
        item = self.AVB_ListView.item(0)
        item.setText(_translate("DutConf_Form", "0"))
        item = self.AVB_ListView.item(1)
        item.setText(_translate("DutConf_Form", "1"))
        item = self.AVB_ListView.item(2)
        item.setText(_translate("DutConf_Form", "2"))
        item = self.AVB_ListView.item(3)
        item.setText(_translate("DutConf_Form", "3"))
        item = self.AVB_ListView.item(4)
        item.setText(_translate("DutConf_Form", "4"))
        item = self.AVB_ListView.item(5)
        item.setText(_translate("DutConf_Form", "5"))
        item = self.AVB_ListView.item(6)
        item.setText(_translate("DutConf_Form", "6"))
        item = self.AVB_ListView.item(7)
        item.setText(_translate("DutConf_Form", "7"))
        item = self.AVB_ListView.item(8)
        item.setText(_translate("DutConf_Form", "8"))
        item = self.AVB_ListView.item(9)
        item.setText(_translate("DutConf_Form", "9"))
        item = self.AVB_ListView.item(10)
        item.setText(_translate("DutConf_Form", "10"))
        item = self.AVB_ListView.item(11)
        item.setText(_translate("DutConf_Form", "11"))
        item = self.AVB_ListView.item(12)
        item.setText(_translate("DutConf_Form", "13"))
        item = self.AVB_ListView.item(13)
        item.setText(_translate("DutConf_Form", "14"))
        item = self.AVB_ListView.item(14)
        item.setText(_translate("DutConf_Form", "15"))
        self.AVB_ListView.setSortingEnabled(__sortingEnabled)
        self.DesignPath_label.setText(_translate("DutConf_Form", "Design Path"))
        self.DesignPath_toolButton.setText(_translate("DutConf_Form", "..."))
        self.RecordConf_Groupbox.setTitle(_translate("DutConf_Form", "Record Configurations"))
        self.RecordDir_label.setText(_translate("DutConf_Form", "Record Directory"))
        self.RecordDir_toolButton.setText(_translate("DutConf_Form", "..."))
        self.Snapshots_GroupBox.setTitle(_translate("DutConf_Form", "SnapShots Number"))
        self.ConfigType_label.setText(_translate("DutConf_Form", "Config Type"))
        self.ConfigType_comboBox.setItemText(0, _translate("DutConf_Form", "Range"))
        self.ConfigType_comboBox.setItemText(1, _translate("DutConf_Form", "List"))
        self.ConfigType_comboBox.setItemText(2, _translate("DutConf_Form", "Value"))
        self.FromConfigValue_label.setText(_translate("DutConf_Form", "From"))
        self.ToConfigValue_label.setText(_translate("DutConf_Form", "To"))
        self.ReplyConf_groupbox.setTitle(_translate("DutConf_Form", "Reply Configurations"))
        self.ReplyDir_label.setText(_translate("DutConf_Form", "Reply Directory"))
        self.ReplyDir_toolButton.setText(_translate("DutConf_Form", "..."))
        self.ReplySnapshotName_label.setText(_translate("DutConf_Form", "Replay Snapshot Name"))
        self.DPIConf_groupbox.setTitle(_translate("DutConf_Form", "DPI Configurations"))
        self.DPILaunchMode_label.setText(_translate("DutConf_Form", "DPI Launch Mode"))
        self.DPILaunchType_label.setText(_translate("DutConf_Form", "DPI Launch Type"))
        self.DPILaunchType_comboBox.setItemText(0, _translate("DutConf_Form", "Emulation"))
        self.DPILaunchType_comboBox.setItemText(1, _translate("DutConf_Form", "Simulation"))
        self.DPILaunchType_comboBox.setItemText(2, _translate("DutConf_Form", "Emulation_Velclkgen"))
        self.DPILaunchType_comboBox.setItemText(3, _translate("DutConf_Form", "Simulation_Velclkgen"))
        self.DPIAdditionalArgGroupBox.setTitle(_translate("DutConf_Form", "DPI Additional Arguments"))
        self.ArgName_label.setText(_translate("DutConf_Form", "Argument Key"))
        self.ArgValue_label.setText(_translate("DutConf_Form", "Argument Value"))
        self.AddArgButton.setText(_translate("DutConf_Form", "Add"))
        self.DPIAdditionalArg_groupBox.setTitle(_translate("DutConf_Form", "DPI Additional Env Variables"))
        self.EnvVarName_label.setText(_translate("DutConf_Form", "Variable Key"))
        self.EnvVarValue_label.setText(_translate("DutConf_Form", "Variable Value"))
        self.AddEnv.setText(_translate("DutConf_Form", "Add"))
        self.CustomComConf_checkbox.setText(_translate("DutConf_Form", "Use Custom Comodels Config"))
