# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task_Tab(object):
    def setupUi(self, Task_Tab):
        Task_Tab.setObjectName("Task_Tab")
        Task_Tab.resize(771, 552)
        Task_Tab.setStyleSheet("QWidget{\n"
"background-color:rgb(37, 40, 50);\n"
"    color: white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Task_Tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Task_Tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::pane{\n"
"border-color:none;\n"
"}\n"
"QTabWidget:tab-bar {\n"
"\n"
"border-color:none;\n"
"}\n"
"QTabBar:tab:selected{\n"
"background-color:#282c37;\n"
"color:white;\n"
"}\n"
"QTabBar:tab:!selected{\n"
"background-color:#1b1d22;\n"
"color:white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.running_config = QtWidgets.QWidget()
        self.running_config.setObjectName("running_config")
        self.tabWidget.addTab(self.running_config, "")
        self.environments = QtWidgets.QWidget()
        self.environments.setStyleSheet("\n"
"\n"
"")
        self.environments.setObjectName("environments")
        self.formLayout_3 = QtWidgets.QFormLayout(self.environments)
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.databaseLabel_2 = QtWidgets.QLabel(self.environments)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.databaseLabel_2.setFont(font)
        self.databaseLabel_2.setLineWidth(0)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.horizontalLayout_5.addWidget(self.databaseLabel_2)
        self.lineEditDatabasePath_2 = QtWidgets.QLineEdit(self.environments)
        self.lineEditDatabasePath_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_2.setStyleSheet("")
        self.lineEditDatabasePath_2.setObjectName("lineEditDatabasePath_2")
        self.horizontalLayout_5.addWidget(self.lineEditDatabasePath_2)
        self.toolButtonBrowseDatabase_3 = QtWidgets.QToolButton(self.environments)
        self.toolButtonBrowseDatabase_3.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBrowseDatabase_3.setIcon(icon)
        self.toolButtonBrowseDatabase_3.setObjectName("toolButtonBrowseDatabase_3")
        self.horizontalLayout_5.addWidget(self.toolButtonBrowseDatabase_3)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.environments)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_2 = QtWidgets.QRadioButton(self.environments)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.databaseLabel_4 = QtWidgets.QLabel(self.environments)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.databaseLabel_4.setFont(font)
        self.databaseLabel_4.setLineWidth(0)
        self.databaseLabel_4.setObjectName("databaseLabel_4")
        self.horizontalLayout_6.addWidget(self.databaseLabel_4)
        self.lineEditDatabasePath_3 = QtWidgets.QLineEdit(self.environments)
        self.lineEditDatabasePath_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_3.setStyleSheet("")
        self.lineEditDatabasePath_3.setObjectName("lineEditDatabasePath_3")
        self.horizontalLayout_6.addWidget(self.lineEditDatabasePath_3)
        self.databaseLabel_3 = QtWidgets.QLabel(self.environments)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.databaseLabel_3.setFont(font)
        self.databaseLabel_3.setLineWidth(0)
        self.databaseLabel_3.setObjectName("databaseLabel_3")
        self.horizontalLayout_6.addWidget(self.databaseLabel_3)
        self.lineEditDatabasePath_4 = QtWidgets.QLineEdit(self.environments)
        self.lineEditDatabasePath_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_4.setStyleSheet("")
        self.lineEditDatabasePath_4.setObjectName("lineEditDatabasePath_4")
        self.horizontalLayout_6.addWidget(self.lineEditDatabasePath_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.radioButton_3 = QtWidgets.QRadioButton(self.environments)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.gridLayout_6.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_6)
        self.tabWidget.addTab(self.environments, "")
        self.design = QtWidgets.QWidget()
        self.design.setStyleSheet("")
        self.design.setObjectName("design")
        self.formLayout = QtWidgets.QFormLayout(self.design)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(51, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(self.design)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 725, 85))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.scrollArea)
        self.tabWidget.addTab(self.design, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Task_Tab)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Task_Tab)

    def retranslateUi(self, Task_Tab):
        _translate = QtCore.QCoreApplication.translate
        Task_Tab.setWindowTitle(_translate("Task_Tab", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.running_config), _translate("Task_Tab", "Running Configurations"))
        self.databaseLabel_2.setText(_translate("Task_Tab", "Design Path"))
        self.toolButtonBrowseDatabase_3.setText(_translate("Task_Tab", "..."))
        self.radioButton.setText(_translate("Task_Tab", "All"))
        self.radioButton_2.setText(_translate("Task_Tab", "Range"))
        self.databaseLabel_4.setText(_translate("Task_Tab", "From"))
        self.databaseLabel_3.setText(_translate("Task_Tab", "To"))
        self.radioButton_3.setText(_translate("Task_Tab", "Binary Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.environments), _translate("Task_Tab", "Environments"))
        self.pushButton.setText(_translate("Task_Tab", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.design), _translate("Task_Tab", "Design"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Task_Tab = QtWidgets.QWidget()
    ui = Ui_Task_Tab()
    ui.setupUi(Task_Tab)
    Task_Tab.show()
    sys.exit(app.exec_())
