# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Siemens diploma\Anomalies-Tracker-Siemens-Academy\UiFiles\Task_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Task_Tab(object):
    def setupUi(self, Task_Tab):
        Task_Tab.setObjectName("Task_Tab")
        Task_Tab.resize(759, 449)
        Task_Tab.setStyleSheet("QWidget{\n"
"background-color:rgb(37, 40, 50);\n"
"    color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Task_Tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Task_Tab)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::pane{\n"
"border-color:none;\n"
"}\n"
"QTabWidget:tab-bar {\n"
"\n"
"border-color:none;\n"
"}\n"
"QTabBar:tab:selected{\n"
"background-color:#282c37;\n"
"color:white;\n"
"}\n"
"QTabBar:tab:!selected{\n"
"background-color:#1b1d22;\n"
"color:white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 0px solid rgb(37, 39, 48);\n"
"    height: 30px;\n"
"    border-radius: 15px;\n"
"    color: white;\n"
"    padding-left: 20px;\n"
"    padding-right: 20px;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88)\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 3px solid rgb(91, 101, 124);\n"
"    color: white;\n"
"}\n"
"QLineEdit:disabled {\n"
"    background-color: #808080;\n"
"}\n"
"/* ToolButton */\n"
"QToolButton {\n"
"    border: 0px;\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"}\n"
"QToolButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QToolButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    margin-right:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.running_config = QtWidgets.QWidget()
        self.running_config.setObjectName("running_config")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.running_config)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(self.running_config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(51, 41))
        self.pushButton_4.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.running_config)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaRunningConfig = QtWidgets.QWidget()
        self.scrollAreaRunningConfig.setGeometry(QtCore.QRect(0, 0, 721, 339))
        self.scrollAreaRunningConfig.setObjectName("scrollAreaRunningConfig")
        self.scrollArea_2.setWidget(self.scrollAreaRunningConfig)
        self.gridLayout_2.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.running_config, "")
        self.environments = QtWidgets.QWidget()
        self.environments.setStyleSheet("")
        self.environments.setObjectName("environments")
        self.formLayout_2 = QtWidgets.QFormLayout(self.environments)
        self.formLayout_2.setObjectName("formLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.environments)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.databaseLabel_5 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_5.setFont(font)
        self.databaseLabel_5.setLineWidth(0)
        self.databaseLabel_5.setObjectName("databaseLabel_5")
        self.horizontalLayout_7.addWidget(self.databaseLabel_5)
        self.lineEditDatabasePath_5 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEditDatabasePath_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_5.setStyleSheet("")
        self.lineEditDatabasePath_5.setObjectName("lineEditDatabasePath_5")
        self.horizontalLayout_7.addWidget(self.lineEditDatabasePath_5)
        self.toolButtonBrowseDatabase_4 = QtWidgets.QToolButton(self.widget_2)
        self.toolButtonBrowseDatabase_4.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/folder_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonBrowseDatabase_4.setIcon(icon)
        self.toolButtonBrowseDatabase_4.setObjectName("toolButtonBrowseDatabase_4")
        self.horizontalLayout_7.addWidget(self.toolButtonBrowseDatabase_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.widget_2)
        self.widget = QtWidgets.QWidget(self.environments)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.databaseLabel_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_2.setFont(font)
        self.databaseLabel_2.setLineWidth(0)
        self.databaseLabel_2.setObjectName("databaseLabel_2")
        self.horizontalLayout_5.addWidget(self.databaseLabel_2)
        self.lineEditDatabasePath_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEditDatabasePath_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_2.setStyleSheet("")
        self.lineEditDatabasePath_2.setObjectName("lineEditDatabasePath_2")
        self.horizontalLayout_5.addWidget(self.lineEditDatabasePath_2)
        self.toolButtonBrowseDatabase_3 = QtWidgets.QToolButton(self.widget)
        self.toolButtonBrowseDatabase_3.setStyleSheet("")
        self.toolButtonBrowseDatabase_3.setIcon(icon)
        self.toolButtonBrowseDatabase_3.setObjectName("toolButtonBrowseDatabase_3")
        self.horizontalLayout_5.addWidget(self.toolButtonBrowseDatabase_3)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.databaseLabel_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_4.setFont(font)
        self.databaseLabel_4.setLineWidth(0)
        self.databaseLabel_4.setObjectName("databaseLabel_4")
        self.horizontalLayout_6.addWidget(self.databaseLabel_4)
        self.lineEditDatabasePath_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEditDatabasePath_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_3.setStyleSheet("")
        self.lineEditDatabasePath_3.setObjectName("lineEditDatabasePath_3")
        self.horizontalLayout_6.addWidget(self.lineEditDatabasePath_3)
        self.databaseLabel_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_3.setFont(font)
        self.databaseLabel_3.setLineWidth(0)
        self.databaseLabel_3.setObjectName("databaseLabel_3")
        self.horizontalLayout_6.addWidget(self.databaseLabel_3)
        self.lineEditDatabasePath_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEditDatabasePath_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_4.setStyleSheet("")
        self.lineEditDatabasePath_4.setObjectName("lineEditDatabasePath_4")
        self.horizontalLayout_6.addWidget(self.lineEditDatabasePath_4)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.databaseLabel_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_7.setFont(font)
        self.databaseLabel_7.setLineWidth(0)
        self.databaseLabel_7.setObjectName("databaseLabel_7")
        self.horizontalLayout_2.addWidget(self.databaseLabel_7)
        self.lineEditDatabasePath_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEditDatabasePath_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_7.setStyleSheet("")
        self.lineEditDatabasePath_7.setObjectName("lineEditDatabasePath_7")
        self.horizontalLayout_2.addWidget(self.lineEditDatabasePath_7)
        self.databaseLabel_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.databaseLabel_6.setFont(font)
        self.databaseLabel_6.setLineWidth(0)
        self.databaseLabel_6.setObjectName("databaseLabel_6")
        self.horizontalLayout_2.addWidget(self.databaseLabel_6)
        self.lineEditDatabasePath_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEditDatabasePath_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditDatabasePath_6.setStyleSheet("")
        self.lineEditDatabasePath_6.setObjectName("lineEditDatabasePath_6")
        self.horizontalLayout_2.addWidget(self.lineEditDatabasePath_6)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.environments)
        self.pushButton_2.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.environments)
        self.pushButton_3.setMinimumSize(QtCore.QSize(211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.tabWidget.addTab(self.environments, "")
        self.design = QtWidgets.QWidget()
        self.design.setStyleSheet("")
        self.design.setObjectName("design")
        self.formLayout = QtWidgets.QFormLayout(self.design)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(658, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(51, 41))
        self.pushButton.setMaximumSize(QtCore.QSize(51, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(self.design)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 721, 339))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.scrollArea)
        self.tabWidget.addTab(self.design, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Task_Tab)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Task_Tab)

    def retranslateUi(self, Task_Tab):
        _translate = QtCore.QCoreApplication.translate
        Task_Tab.setWindowTitle(_translate("Task_Tab", "Form"))
        self.pushButton_4.setText(_translate("Task_Tab", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.running_config), _translate("Task_Tab", "Running Configurations"))
        self.databaseLabel_5.setText(_translate("Task_Tab", "File Path"))
        self.toolButtonBrowseDatabase_4.setText(_translate("Task_Tab", "..."))
        self.databaseLabel_2.setText(_translate("Task_Tab", "Parent Directory"))
        self.toolButtonBrowseDatabase_3.setText(_translate("Task_Tab", "..."))
        self.radioButton.setText(_translate("Task_Tab", "All"))
        self.radioButton_2.setText(_translate("Task_Tab", "Range"))
        self.databaseLabel_4.setText(_translate("Task_Tab", "From"))
        self.databaseLabel_3.setText(_translate("Task_Tab", "To"))
        self.radioButton_3.setText(_translate("Task_Tab", "Binary Search"))
        self.databaseLabel_7.setText(_translate("Task_Tab", "From"))
        self.databaseLabel_6.setText(_translate("Task_Tab", "To"))
        self.pushButton_2.setText(_translate("Task_Tab", "Add Directory"))
        self.pushButton_3.setText(_translate("Task_Tab", "Add File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.environments), _translate("Task_Tab", "Environments"))
        self.pushButton.setText(_translate("Task_Tab", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.design), _translate("Task_Tab", "Design"))
