# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jobs.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Jobs(object):
    def setupUi(self, Jobs):
        Jobs.setObjectName("Jobs")
        Jobs.resize(796, 606)
        Jobs.setStyleSheet("QWidget{\n"
"background-color:rgb(37, 40, 50);\n"
"    color: white;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QFrame QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Jobs)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Jobs)
        self.scrollArea.setStyleSheet("color:rgb(37, 40, 50);\n"
"QTableWidget::item{\n"
"background-color:rgb(37, 40, 50);\n"
"\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.Jobs_scrollArea = QtWidgets.QWidget()
        self.Jobs_scrollArea.setGeometry(QtCore.QRect(0, 0, 772, 582))
        self.Jobs_scrollArea.setStyleSheet("QWidget::pane{\n"
"border-color:none;\n"
"\n"
"background-color:rgb(37, 40, 50);\n"
"}\n"
"\n"
"")
        self.Jobs_scrollArea.setObjectName("Jobs_scrollArea")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Jobs_scrollArea)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.selectall_widget = QtWidgets.QWidget(self.Jobs_scrollArea)
        self.selectall_widget.setObjectName("selectall_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.selectall_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectall_horizontalLayout = QtWidgets.QHBoxLayout()
        self.selectall_horizontalLayout.setObjectName("selectall_horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.selectall_horizontalLayout.addItem(spacerItem)
        self.selectall_pushButton = QtWidgets.QPushButton(self.selectall_widget)
        self.selectall_pushButton.setMinimumSize(QtCore.QSize(143, 54))
        self.selectall_pushButton.setStyleSheet("QPushButton {\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    background-color: rgb(33, 188, 180);\n"
"    color: rgb(255, 255, 255);\n"
"    margin:10px;\n"
"    padding:5px;\n"
"font:bold 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(102, 109, 122);\n"
"    color: rgb(168, 168, 168);\n"
"}")
        self.selectall_pushButton.setObjectName("selectall_pushButton")
        self.selectall_horizontalLayout.addWidget(self.selectall_pushButton)
        self.horizontalLayout_2.addLayout(self.selectall_horizontalLayout)
        self.gridLayout_2.addWidget(self.selectall_widget, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(580, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Run_pushButton = QtWidgets.QPushButton(self.Jobs_scrollArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Run_pushButton.sizePolicy().hasHeightForWidth())
        self.Run_pushButton.setSizePolicy(sizePolicy)
        self.Run_pushButton.setMinimumSize(QtCore.QSize(100, 35))
        self.Run_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color:White;\n"
"    margin-right:5px;\n"
"    border-radius: 10px;\n"
"    border: 0px solid rgb(52, 59, 72);\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(230, 96, 96);\n"
"    border: 5px solid transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 7px solid transparent;\n"
"}\n"
"\n"
"\n"
"")
        self.Run_pushButton.setObjectName("Run_pushButton")
        self.horizontalLayout.addWidget(self.Run_pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.Jobs_table = QtWidgets.QTableWidget(self.Jobs_scrollArea)
        self.Jobs_table.setStyleSheet("QTableWidget::item {\n"
"background-color:rgb(37, 40, 50);\n"
"color:white;\n"
"}")
        self.Jobs_table.setObjectName("Jobs_table")
        self.Jobs_table.setColumnCount(9)
        self.Jobs_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Jobs_table.setHorizontalHeaderItem(8, item)
        self.gridLayout_2.addWidget(self.Jobs_table, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.Jobs_scrollArea)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Jobs)
        QtCore.QMetaObject.connectSlotsByName(Jobs)

    def retranslateUi(self, Jobs):
        _translate = QtCore.QCoreApplication.translate
        Jobs.setWindowTitle(_translate("Jobs", "Form"))
        self.selectall_pushButton.setText(_translate("Jobs", "Select All"))
        self.Run_pushButton.setText(_translate("Jobs", "Run"))
        item = self.Jobs_table.horizontalHeaderItem(0)
        item.setText(_translate("Jobs", "Include"))
        item = self.Jobs_table.horizontalHeaderItem(1)
        item.setText(_translate("Jobs", "ID"))
        item = self.Jobs_table.horizontalHeaderItem(2)
        item.setText(_translate("Jobs", "Prerequisite Task"))
        item = self.Jobs_table.horizontalHeaderItem(3)
        item.setText(_translate("Jobs", "Prerequisite Job"))
        item = self.Jobs_table.horizontalHeaderItem(4)
        item.setText(_translate("Jobs", "Script Path"))
        item = self.Jobs_table.horizontalHeaderItem(5)
        item.setText(_translate("Jobs", "Running Configurations"))
        item = self.Jobs_table.horizontalHeaderItem(6)
        item.setText(_translate("Jobs", "Build Path"))
        item = self.Jobs_table.horizontalHeaderItem(7)
        item.setText(_translate("Jobs", "Design Path"))
        item = self.Jobs_table.horizontalHeaderItem(8)
        item.setText(_translate("Jobs", "Design Configurations"))
